// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vseed/Detail.html:1
package vseed

//line views/vseed/Detail.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/seed"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/view"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vseed/Detail.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vseed/Detail.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vseed/Detail.html:10
type Detail struct {
	layout.Basic
	Model *seed.Seed
	Paths []string
}

//line views/vseed/Detail.html:16
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vseed/Detail.html:16
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-seed"><button type="button">`)
//line views/vseed/Detail.html:19
	components.StreamSVGButton(qw422016, "file", ps)
//line views/vseed/Detail.html:19
	qw422016.N().S(` JSON</button></a>
      <a href="`)
//line views/vseed/Detail.html:20
	qw422016.E().S(p.Model.WebPath(p.Paths...))
//line views/vseed/Detail.html:20
	qw422016.N().S(`/edit"><button>`)
//line views/vseed/Detail.html:20
	components.StreamSVGButton(qw422016, "edit", ps)
//line views/vseed/Detail.html:20
	qw422016.N().S(` Edit</button></a>
    </div>
    <h3>`)
//line views/vseed/Detail.html:22
	components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vseed/Detail.html:22
	qw422016.N().S(` `)
//line views/vseed/Detail.html:22
	qw422016.E().S(p.Model.TitleString())
//line views/vseed/Detail.html:22
	qw422016.N().S(`</h3>
    <div><a href="`)
//line views/vseed/Detail.html:23
	qw422016.E().S(seed.Route(p.Paths...))
//line views/vseed/Detail.html:23
	qw422016.N().S(`"><em>Seed</em></a></div>
    <div class="mt overflow full-width">
      <table>
        <tbody>
          <tr>
            <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
            <td>`)
//line views/vseed/Detail.html:29
	view.StreamUUID(qw422016, &p.Model.ID)
//line views/vseed/Detail.html:29
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Name</th>
            <td><strong>`)
//line views/vseed/Detail.html:33
	view.StreamString(qw422016, p.Model.Name)
//line views/vseed/Detail.html:33
	qw422016.N().S(`</strong></td>
          </tr>
          <tr>
            <th class="shrink" title="Integer">Size</th>
            <td>`)
//line views/vseed/Detail.html:37
	qw422016.N().D(p.Model.Size)
//line views/vseed/Detail.html:37
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="JSON object">Obj</th>
            <td>`)
//line views/vseed/Detail.html:41
	components.StreamJSON(qw422016, p.Model.Obj)
//line views/vseed/Detail.html:41
	qw422016.N().S(`</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
`)
//line views/vseed/Detail.html:48
	qw422016.N().S(`  `)
//line views/vseed/Detail.html:49
	components.StreamJSONModal(qw422016, "seed", "Seed JSON", p.Model, 1)
//line views/vseed/Detail.html:49
	qw422016.N().S(`
`)
//line views/vseed/Detail.html:50
}

//line views/vseed/Detail.html:50
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vseed/Detail.html:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vseed/Detail.html:50
	p.StreamBody(qw422016, as, ps)
//line views/vseed/Detail.html:50
	qt422016.ReleaseWriter(qw422016)
//line views/vseed/Detail.html:50
}

//line views/vseed/Detail.html:50
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vseed/Detail.html:50
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vseed/Detail.html:50
	p.WriteBody(qb422016, as, ps)
//line views/vseed/Detail.html:50
	qs422016 := string(qb422016.B)
//line views/vseed/Detail.html:50
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vseed/Detail.html:50
	return qs422016
//line views/vseed/Detail.html:50
}
