// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vseed/List.html:1
package vseed

//line views/vseed/List.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/app/seed"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vseed/List.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vseed/List.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vseed/List.html:10
type List struct {
	layout.Basic
	Models seed.Seeds
	Params filter.ParamSet
}

//line views/vseed/List.html:16
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vseed/List.html:16
	qw422016.N().S(`
  <div class="card">
    <div class="right mrs large-buttons">
`)
//line views/vseed/List.html:19
	if len(p.Models) > 1 {
//line views/vseed/List.html:19
		qw422016.N().S(`<a href="/seed/_random"><button>`)
//line views/vseed/List.html:19
		components.StreamSVGButton(qw422016, "gift", ps)
//line views/vseed/List.html:19
		qw422016.N().S(` Random</button></a>`)
//line views/vseed/List.html:19
	}
//line views/vseed/List.html:19
	qw422016.N().S(`      <a href="/seed/_new"><button>`)
//line views/vseed/List.html:20
	components.StreamSVGButton(qw422016, "plus", ps)
//line views/vseed/List.html:20
	qw422016.N().S(` New</button></a>
    </div>
    <h3>`)
//line views/vseed/List.html:22
	components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vseed/List.html:22
	qw422016.N().S(` `)
//line views/vseed/List.html:22
	qw422016.E().S(ps.Title)
//line views/vseed/List.html:22
	qw422016.N().S(`</h3>
`)
//line views/vseed/List.html:23
	if len(p.Models) == 0 {
//line views/vseed/List.html:23
		qw422016.N().S(`    <div class="mt"><em>No seeds available</em></div>
`)
//line views/vseed/List.html:25
	} else {
//line views/vseed/List.html:25
		qw422016.N().S(`    <div class="mt">
      `)
//line views/vseed/List.html:27
		StreamTable(qw422016, p.Models, p.Params, as, ps)
//line views/vseed/List.html:27
		qw422016.N().S(`
    </div>
`)
//line views/vseed/List.html:29
	}
//line views/vseed/List.html:29
	qw422016.N().S(`  </div>
`)
//line views/vseed/List.html:31
}

//line views/vseed/List.html:31
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vseed/List.html:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vseed/List.html:31
	p.StreamBody(qw422016, as, ps)
//line views/vseed/List.html:31
	qt422016.ReleaseWriter(qw422016)
//line views/vseed/List.html:31
}

//line views/vseed/List.html:31
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vseed/List.html:31
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vseed/List.html:31
	p.WriteBody(qb422016, as, ps)
//line views/vseed/List.html:31
	qs422016 := string(qb422016.B)
//line views/vseed/List.html:31
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vseed/List.html:31
	return qs422016
//line views/vseed/List.html:31
}
