// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vcapital/Detail.html:2
package vcapital

//line views/vcapital/Detail.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/capital"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/view"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vcapital/Detail.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vcapital/Detail.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vcapital/Detail.html:11
type Detail struct {
	layout.Basic
	Model *capital.Capital
}

//line views/vcapital/Detail.html:16
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vcapital/Detail.html:16
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-capital"><button type="button">JSON</button></a>
      <a href="`)
//line views/vcapital/Detail.html:20
	qw422016.E().S(p.Model.WebPath())
//line views/vcapital/Detail.html:20
	qw422016.N().S(`/edit"><button>`)
//line views/vcapital/Detail.html:20
	components.StreamSVGRef(qw422016, "edit", 15, 15, "icon", ps)
//line views/vcapital/Detail.html:20
	qw422016.N().S(`Edit</button></a>
    </div>
    <h3>`)
//line views/vcapital/Detail.html:22
	components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vcapital/Detail.html:22
	qw422016.N().S(` `)
//line views/vcapital/Detail.html:22
	qw422016.E().S(p.Model.TitleString())
//line views/vcapital/Detail.html:22
	qw422016.N().S(`</h3>
    <div><a href="/capital"><em>Capital</em></a></div>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="String text">ID</th>
          <td>`)
//line views/vcapital/Detail.html:28
	view.StreamString(qw422016, p.Model.ID)
//line views/vcapital/Detail.html:28
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Name</th>
          <td><strong>`)
//line views/vcapital/Detail.html:32
	view.StreamString(qw422016, p.Model.Name)
//line views/vcapital/Detail.html:32
	qw422016.N().S(`</strong></td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Birthday</th>
          <td>`)
//line views/vcapital/Detail.html:36
	view.StreamTimestamp(qw422016, &p.Model.Birthday)
//line views/vcapital/Detail.html:36
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format (optional)">Deathday</th>
          <td>`)
//line views/vcapital/Detail.html:40
	view.StreamTimestamp(qw422016, p.Model.Deathday)
//line views/vcapital/Detail.html:40
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vcapital/Detail.html:46
	qw422016.N().S(`  `)
//line views/vcapital/Detail.html:47
	components.StreamJSONModal(qw422016, "capital", "Capital JSON", p.Model, 1)
//line views/vcapital/Detail.html:47
	qw422016.N().S(`
`)
//line views/vcapital/Detail.html:48
}

//line views/vcapital/Detail.html:48
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vcapital/Detail.html:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vcapital/Detail.html:48
	p.StreamBody(qw422016, as, ps)
//line views/vcapital/Detail.html:48
	qt422016.ReleaseWriter(qw422016)
//line views/vcapital/Detail.html:48
}

//line views/vcapital/Detail.html:48
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vcapital/Detail.html:48
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vcapital/Detail.html:48
	p.WriteBody(qb422016, as, ps)
//line views/vcapital/Detail.html:48
	qs422016 := string(qb422016.B)
//line views/vcapital/Detail.html:48
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vcapital/Detail.html:48
	return qs422016
//line views/vcapital/Detail.html:48
}
