// Code generated by qtc from "Edit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vgroup/Edit.html:2
package vgroup

//line views/vgroup/Edit.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/group"
	"github.com/kyleu/pftest/app/util"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vgroup/Edit.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vgroup/Edit.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vgroup/Edit.html:11
type Edit struct {
	layout.Basic
	Model *group.Group
	IsNew bool
}

//line views/vgroup/Edit.html:17
func (p *Edit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vgroup/Edit.html:17
	qw422016.N().S(`
  <div class="card">
`)
//line views/vgroup/Edit.html:19
	if p.IsNew {
//line views/vgroup/Edit.html:19
		qw422016.N().S(`    <div class="right"><a href="/group/random"><button>Random</button></a></div>
    <h3>`)
//line views/vgroup/Edit.html:21
		components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vgroup/Edit.html:21
		qw422016.N().S(` New Group</h3>
    <form action="/group/new" class="mt" method="post">
`)
//line views/vgroup/Edit.html:23
	} else {
//line views/vgroup/Edit.html:23
		qw422016.N().S(`    <div class="right"><a href="`)
//line views/vgroup/Edit.html:24
		qw422016.E().S(p.Model.WebPath())
//line views/vgroup/Edit.html:24
		qw422016.N().S(`/delete" onclick="return confirm('Are you sure you wish to delete group [`)
//line views/vgroup/Edit.html:24
		qw422016.E().S(p.Model.String())
//line views/vgroup/Edit.html:24
		qw422016.N().S(`]?')"><button>Delete</button></a></div>
    <h3>`)
//line views/vgroup/Edit.html:25
		components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vgroup/Edit.html:25
		qw422016.N().S(` Edit Group [`)
//line views/vgroup/Edit.html:25
		qw422016.E().S(p.Model.String())
//line views/vgroup/Edit.html:25
		qw422016.N().S(`]</h3>
`)
//line views/vgroup/Edit.html:26
	}
//line views/vgroup/Edit.html:26
	qw422016.N().S(`    <form action="" method="post">
      <table class="mt expanded">
        <tbody>
          `)
//line views/vgroup/Edit.html:30
	if p.IsNew {
//line views/vgroup/Edit.html:30
		components.StreamTableInput(qw422016, "id", "ID", p.Model.ID, 5, "String text")
//line views/vgroup/Edit.html:30
	}
//line views/vgroup/Edit.html:30
	qw422016.N().S(`
          `)
//line views/vgroup/Edit.html:31
	components.StreamTableInput(qw422016, "child", "Child", p.Model.Child, 5, "String text")
//line views/vgroup/Edit.html:31
	qw422016.N().S(`
          `)
//line views/vgroup/Edit.html:32
	components.StreamTableTextarea(qw422016, "data", "Data", 8, util.ToJSON(p.Model.Data), 5, "JSON object")
//line views/vgroup/Edit.html:32
	qw422016.N().S(`
          `)
//line views/vgroup/Edit.html:33
	components.StreamTableInputTimestamp(qw422016, "deleted", "Deleted", p.Model.Deleted, 5, "Date and time, in almost any format (optional)")
//line views/vgroup/Edit.html:33
	qw422016.N().S(`
          <tr><td colspan="2"><button type="submit">Save Changes</button></td></tr>
        </tbody>
      </table>
    </form>
  </div>
`)
//line views/vgroup/Edit.html:39
}

//line views/vgroup/Edit.html:39
func (p *Edit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vgroup/Edit.html:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vgroup/Edit.html:39
	p.StreamBody(qw422016, as, ps)
//line views/vgroup/Edit.html:39
	qt422016.ReleaseWriter(qw422016)
//line views/vgroup/Edit.html:39
}

//line views/vgroup/Edit.html:39
func (p *Edit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vgroup/Edit.html:39
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vgroup/Edit.html:39
	p.WriteBody(qb422016, as, ps)
//line views/vgroup/Edit.html:39
	qs422016 := string(qb422016.B)
//line views/vgroup/Edit.html:39
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vgroup/Edit.html:39
	return qs422016
//line views/vgroup/Edit.html:39
}
