// Code generated by qtc from "OpenAPI.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vopenapi/OpenAPI.html:1
package vopenapi

//line views/vopenapi/OpenAPI.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vopenapi/OpenAPI.html:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vopenapi/OpenAPI.html:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vopenapi/OpenAPI.html:7
type OpenAPI struct {
	layout.Basic
	URL string
}

//line views/vopenapi/OpenAPI.html:12
func (p *OpenAPI) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vopenapi/OpenAPI.html:12
	qw422016.N().S(`
  <div id="swagger-ui"></div>
  <link rel="stylesheet" type="text/css" href="/assets/openapi/swagger-ui.css" />
  <script src="/assets/openapi/swagger-ui-bundle.js" defer="defer"></script>
  <script src="/assets/openapi/swagger-ui-standalone-preset.js" defer="defer"></script>
  <script>
    window.onload = function() {
      window.ui = SwaggerUIBundle({
        url: "`)
//line views/vopenapi/OpenAPI.html:20
	qw422016.E().S(p.URL)
//line views/vopenapi/OpenAPI.html:20
	qw422016.N().S(`",
        dom_id: '#swagger-ui',
        deepLinking: true,
        displayRequestDuration: true,
        filter: true,
        tryItOutEnabled: true,
        presets: [
          SwaggerUIBundle.presets.apis
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ]
      });
    };
  </script>
`)
//line views/vopenapi/OpenAPI.html:35
}

//line views/vopenapi/OpenAPI.html:35
func (p *OpenAPI) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vopenapi/OpenAPI.html:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vopenapi/OpenAPI.html:35
	p.StreamBody(qw422016, as, ps)
//line views/vopenapi/OpenAPI.html:35
	qt422016.ReleaseWriter(qw422016)
//line views/vopenapi/OpenAPI.html:35
}

//line views/vopenapi/OpenAPI.html:35
func (p *OpenAPI) Body(as *app.State, ps *cutil.PageState) string {
//line views/vopenapi/OpenAPI.html:35
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vopenapi/OpenAPI.html:35
	p.WriteBody(qb422016, as, ps)
//line views/vopenapi/OpenAPI.html:35
	qs422016 := string(qb422016.B)
//line views/vopenapi/OpenAPI.html:35
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vopenapi/OpenAPI.html:35
	return qs422016
//line views/vopenapi/OpenAPI.html:35
}
