// Code generated by qtc from "History.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vhistory/History.html:2
package vhistory

//line views/vhistory/History.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/history"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vhistory/History.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vhistory/History.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vhistory/History.html:11
type History struct {
	layout.Basic
	Model   *history.History
	History *history.HistoryHistory
}

//line views/vhistory/History.html:17
func (p *History) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vhistory/History.html:17
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vhistory/History.html:19
	components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vhistory/History.html:19
	qw422016.N().S(` History History [`)
//line views/vhistory/History.html:19
	qw422016.E().S(p.History.ID.String())
//line views/vhistory/History.html:19
	qw422016.N().S(`]</h3>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink">ID</th>
          <td>`)
//line views/vhistory/History.html:24
	qw422016.E().S(p.History.ID.String())
//line views/vhistory/History.html:24
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink">History ID</th>
          <td><a href="`)
//line views/vhistory/History.html:28
	qw422016.E().S(p.Model.WebPath())
//line views/vhistory/History.html:28
	qw422016.N().S(`">`)
//line views/vhistory/History.html:28
	qw422016.E().S(p.History.HistoryID)
//line views/vhistory/History.html:28
	qw422016.N().S(`</a></td>
        </tr>
        <tr>
          <th class="shrink">Old</th>
          <td>`)
//line views/vhistory/History.html:32
	components.StreamJSON(qw422016, p.History.Old)
//line views/vhistory/History.html:32
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink">New</th>
          <td>`)
//line views/vhistory/History.html:36
	components.StreamJSON(qw422016, p.History.New)
//line views/vhistory/History.html:36
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink">Changes</th>
          <td>`)
//line views/vhistory/History.html:40
	components.StreamDisplayDiffs(qw422016, p.History.Changes)
//line views/vhistory/History.html:40
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink">Created</th>
          <td>`)
//line views/vhistory/History.html:44
	components.StreamDisplayTimestamp(qw422016, &p.History.Created)
//line views/vhistory/History.html:44
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vhistory/History.html:49
}

//line views/vhistory/History.html:49
func (p *History) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vhistory/History.html:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhistory/History.html:49
	p.StreamBody(qw422016, as, ps)
//line views/vhistory/History.html:49
	qt422016.ReleaseWriter(qw422016)
//line views/vhistory/History.html:49
}

//line views/vhistory/History.html:49
func (p *History) Body(as *app.State, ps *cutil.PageState) string {
//line views/vhistory/History.html:49
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhistory/History.html:49
	p.WriteBody(qb422016, as, ps)
//line views/vhistory/History.html:49
	qs422016 := string(qb422016.B)
//line views/vhistory/History.html:49
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhistory/History.html:49
	return qs422016
//line views/vhistory/History.html:49
}

//line views/vhistory/History.html:51
func StreamHistoryTable(qw422016 *qt422016.Writer, model *history.History, histories history.HistoryHistories, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vhistory/History.html:51
	qw422016.N().S(`
`)
//line views/vhistory/History.html:52
	prms := params.Get("history_history", nil, ps.Logger).Sanitize("history_history")

//line views/vhistory/History.html:52
	qw422016.N().S(`  <table class="mt">
    <thead>
      <tr>
        `)
//line views/vhistory/History.html:56
	components.StreamTableHeaderSimple(qw422016, "history_history", "id", "ID", "System-generated history UUID identifier", prms, ps.URI, ps)
//line views/vhistory/History.html:56
	qw422016.N().S(`
        `)
//line views/vhistory/History.html:57
	components.StreamTableHeaderSimple(qw422016, "history_history", "history_id", "History ID", "String text", prms, ps.URI, ps)
//line views/vhistory/History.html:57
	qw422016.N().S(`
        `)
//line views/vhistory/History.html:58
	components.StreamTableHeaderSimple(qw422016, "history_history", "c", "Changes", "Object changes", prms, ps.URI, ps)
//line views/vhistory/History.html:58
	qw422016.N().S(`
        `)
//line views/vhistory/History.html:59
	components.StreamTableHeaderSimple(qw422016, "history_history", "created", "Created", "Time when history was created", prms, ps.URI, ps)
//line views/vhistory/History.html:59
	qw422016.N().S(`
      </tr>
    </thead>
    <tbody>
`)
//line views/vhistory/History.html:63
	for _, h := range histories {
//line views/vhistory/History.html:63
		qw422016.N().S(`      <tr>
        <td><a href="`)
//line views/vhistory/History.html:65
		qw422016.E().S(model.WebPath())
//line views/vhistory/History.html:65
		qw422016.N().S(`/history/`)
//line views/vhistory/History.html:65
		qw422016.E().S(h.ID.String())
//line views/vhistory/History.html:65
		qw422016.N().S(`">`)
//line views/vhistory/History.html:65
		qw422016.E().S(h.ID.String())
//line views/vhistory/History.html:65
		qw422016.N().S(`</a></td>
        <td><a href="`)
//line views/vhistory/History.html:66
		qw422016.E().S(model.WebPath())
//line views/vhistory/History.html:66
		qw422016.N().S(`">`)
//line views/vhistory/History.html:66
		qw422016.E().S(h.HistoryID)
//line views/vhistory/History.html:66
		qw422016.N().S(`</a></td>
        <td>`)
//line views/vhistory/History.html:67
		components.StreamDisplayDiffs(qw422016, h.Changes)
//line views/vhistory/History.html:67
		qw422016.N().S(`</td>
        <td>`)
//line views/vhistory/History.html:68
		components.StreamDisplayTimestamp(qw422016, &h.Created)
//line views/vhistory/History.html:68
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vhistory/History.html:70
	}
//line views/vhistory/History.html:70
	qw422016.N().S(`    </tbody>
  </table>
`)
//line views/vhistory/History.html:73
}

//line views/vhistory/History.html:73
func WriteHistoryTable(qq422016 qtio422016.Writer, model *history.History, histories history.HistoryHistories, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vhistory/History.html:73
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhistory/History.html:73
	StreamHistoryTable(qw422016, model, histories, params, as, ps)
//line views/vhistory/History.html:73
	qt422016.ReleaseWriter(qw422016)
//line views/vhistory/History.html:73
}

//line views/vhistory/History.html:73
func HistoryTable(model *history.History, histories history.HistoryHistories, params filter.ParamSet, as *app.State, ps *cutil.PageState) string {
//line views/vhistory/History.html:73
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhistory/History.html:73
	WriteHistoryTable(qb422016, model, histories, params, as, ps)
//line views/vhistory/History.html:73
	qs422016 := string(qb422016.B)
//line views/vhistory/History.html:73
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhistory/History.html:73
	return qs422016
//line views/vhistory/History.html:73
}
