// Code generated by qtc from "SVG.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/SVG.html:1
package components

//line views/components/SVG.html:1
import (
	"fmt"
	"strings"

	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/icons"
	"github.com/kyleu/pftest/app/util"
)

//line views/components/SVG.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/SVG.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/SVG.html:11
func StreamSVG(qw422016 *qt422016.Writer, k string) {
//line views/components/SVG.html:12
	if strings.HasPrefix(k, "brand-") {
//line views/components/SVG.html:13
		qw422016.N().S(icons.BrandLibrary().HTML(k))
//line views/components/SVG.html:14
	} else {
//line views/components/SVG.html:15
		if svg, ok := util.SVGLibrary[k]; ok {
//line views/components/SVG.html:16
			qw422016.N().S(svg)
//line views/components/SVG.html:17
		} else {
//line views/components/SVG.html:17
			qw422016.N().S(`<!-- missing icon definition for [`)
//line views/components/SVG.html:18
			qw422016.E().S(k)
//line views/components/SVG.html:18
			qw422016.N().S(`], using default icon -->`)
//line views/components/SVG.html:18
			qw422016.N().S(strings.ReplaceAll(util.SVGLibrary["question"], "-question", "-"+k))
//line views/components/SVG.html:19
		}
//line views/components/SVG.html:20
	}
//line views/components/SVG.html:21
}

//line views/components/SVG.html:21
func WriteSVG(qq422016 qtio422016.Writer, k string) {
//line views/components/SVG.html:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:21
	StreamSVG(qw422016, k)
//line views/components/SVG.html:21
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:21
}

//line views/components/SVG.html:21
func SVG(k string) string {
//line views/components/SVG.html:21
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:21
	WriteSVG(qb422016, k)
//line views/components/SVG.html:21
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:21
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:21
	return qs422016
//line views/components/SVG.html:21
}

//line views/components/SVG.html:23
func StreamSVGRef(qw422016 *qt422016.Writer, k string, w int, h int, cls string, ps *cutil.PageState) {
//line views/components/SVG.html:24
	if k != "" {
//line views/components/SVG.html:26
		ps.AddIcon(k)
		if w == 0 {
			w = 20
		}
		if h == 0 {
			h = 20
		}
		style := fmt.Sprintf("width: %dpx; height: %dpx;", w, h)

//line views/components/SVG.html:31
		if cls == "" {
//line views/components/SVG.html:31
			qw422016.N().S(`<svg style="`)
//line views/components/SVG.html:32
			qw422016.E().S(style)
//line views/components/SVG.html:32
			qw422016.N().S(`"><use xlink:href="#svg-`)
//line views/components/SVG.html:32
			qw422016.E().S(k)
//line views/components/SVG.html:32
			qw422016.N().S(`" /></svg>`)
//line views/components/SVG.html:33
		} else {
//line views/components/SVG.html:33
			qw422016.N().S(`<svg class="`)
//line views/components/SVG.html:34
			qw422016.E().S(cls)
//line views/components/SVG.html:34
			qw422016.N().S(`" style="`)
//line views/components/SVG.html:34
			qw422016.E().S(style)
//line views/components/SVG.html:34
			qw422016.N().S(`"><use xlink:href="#svg-`)
//line views/components/SVG.html:34
			qw422016.E().S(k)
//line views/components/SVG.html:34
			qw422016.N().S(`" /></svg>`)
//line views/components/SVG.html:35
		}
//line views/components/SVG.html:36
	}
//line views/components/SVG.html:37
}

//line views/components/SVG.html:37
func WriteSVGRef(qq422016 qtio422016.Writer, k string, w int, h int, cls string, ps *cutil.PageState) {
//line views/components/SVG.html:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:37
	StreamSVGRef(qw422016, k, w, h, cls, ps)
//line views/components/SVG.html:37
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:37
}

//line views/components/SVG.html:37
func SVGRef(k string, w int, h int, cls string, ps *cutil.PageState) string {
//line views/components/SVG.html:37
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:37
	WriteSVGRef(qb422016, k, w, h, cls, ps)
//line views/components/SVG.html:37
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:37
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:37
	return qs422016
//line views/components/SVG.html:37
}

//line views/components/SVG.html:39
func StreamIcon(qw422016 *qt422016.Writer, k string, size int, cls string, ps *cutil.PageState) {
//line views/components/SVG.html:40
	if strings.Contains(k, "/") {
//line views/components/SVG.html:40
		qw422016.N().S(`<img alt="SVG icon [`)
//line views/components/SVG.html:41
		qw422016.E().S(k)
//line views/components/SVG.html:41
		qw422016.N().S(`]" src="`)
//line views/components/SVG.html:41
		qw422016.E().S(k)
//line views/components/SVG.html:41
		qw422016.N().S(`" style="width:`)
//line views/components/SVG.html:41
		qw422016.N().D(size)
//line views/components/SVG.html:41
		qw422016.N().S(`px; height:`)
//line views/components/SVG.html:41
		qw422016.N().D(size)
//line views/components/SVG.html:41
		qw422016.N().S(`px;" />`)
//line views/components/SVG.html:42
	} else {
//line views/components/SVG.html:43
		StreamSVGRef(qw422016, k, size, size, cls, ps)
//line views/components/SVG.html:44
	}
//line views/components/SVG.html:45
}

//line views/components/SVG.html:45
func WriteIcon(qq422016 qtio422016.Writer, k string, size int, cls string, ps *cutil.PageState) {
//line views/components/SVG.html:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:45
	StreamIcon(qw422016, k, size, cls, ps)
//line views/components/SVG.html:45
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:45
}

//line views/components/SVG.html:45
func Icon(k string, size int, cls string, ps *cutil.PageState) string {
//line views/components/SVG.html:45
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:45
	WriteIcon(qb422016, k, size, cls, ps)
//line views/components/SVG.html:45
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:45
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:45
	return qs422016
//line views/components/SVG.html:45
}

//line views/components/SVG.html:47
func StreamSVGSimple(qw422016 *qt422016.Writer, k string, size int, ps *cutil.PageState) {
//line views/components/SVG.html:48
	StreamSVGRef(qw422016, k, size, size, "", ps)
//line views/components/SVG.html:49
}

//line views/components/SVG.html:49
func WriteSVGSimple(qq422016 qtio422016.Writer, k string, size int, ps *cutil.PageState) {
//line views/components/SVG.html:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:49
	StreamSVGSimple(qw422016, k, size, ps)
//line views/components/SVG.html:49
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:49
}

//line views/components/SVG.html:49
func SVGSimple(k string, size int, ps *cutil.PageState) string {
//line views/components/SVG.html:49
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:49
	WriteSVGSimple(qb422016, k, size, ps)
//line views/components/SVG.html:49
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:49
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:49
	return qs422016
//line views/components/SVG.html:49
}

//line views/components/SVG.html:51
func StreamSVGButton(qw422016 *qt422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:52
	StreamSVGRef(qw422016, k, 14, 14, "icon", ps)
//line views/components/SVG.html:53
}

//line views/components/SVG.html:53
func WriteSVGButton(qq422016 qtio422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:53
	StreamSVGButton(qw422016, k, ps)
//line views/components/SVG.html:53
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:53
}

//line views/components/SVG.html:53
func SVGButton(k string, ps *cutil.PageState) string {
//line views/components/SVG.html:53
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:53
	WriteSVGButton(qb422016, k, ps)
//line views/components/SVG.html:53
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:53
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:53
	return qs422016
//line views/components/SVG.html:53
}

//line views/components/SVG.html:55
func StreamSVGIcon(qw422016 *qt422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:56
	StreamSVGRef(qw422016, k, 18, 18, "icon", ps)
//line views/components/SVG.html:57
}

//line views/components/SVG.html:57
func WriteSVGIcon(qq422016 qtio422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:57
	StreamSVGIcon(qw422016, k, ps)
//line views/components/SVG.html:57
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:57
}

//line views/components/SVG.html:57
func SVGIcon(k string, ps *cutil.PageState) string {
//line views/components/SVG.html:57
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:57
	WriteSVGIcon(qb422016, k, ps)
//line views/components/SVG.html:57
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:57
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:57
	return qs422016
//line views/components/SVG.html:57
}

//line views/components/SVG.html:59
func StreamSVGBreadcrumb(qw422016 *qt422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:60
	StreamSVGRef(qw422016, k, 18, 18, "breadcrumb-icon", ps)
//line views/components/SVG.html:61
}

//line views/components/SVG.html:61
func WriteSVGBreadcrumb(qq422016 qtio422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:61
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:61
	StreamSVGBreadcrumb(qw422016, k, ps)
//line views/components/SVG.html:61
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:61
}

//line views/components/SVG.html:61
func SVGBreadcrumb(k string, ps *cutil.PageState) string {
//line views/components/SVG.html:61
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:61
	WriteSVGBreadcrumb(qb422016, k, ps)
//line views/components/SVG.html:61
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:61
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:61
	return qs422016
//line views/components/SVG.html:61
}

//line views/components/SVG.html:63
func StreamSVGInline(qw422016 *qt422016.Writer, k string, size int, ps *cutil.PageState) {
//line views/components/SVG.html:64
	StreamSVGRef(qw422016, k, size, size, "inline", ps)
//line views/components/SVG.html:65
}

//line views/components/SVG.html:65
func WriteSVGInline(qq422016 qtio422016.Writer, k string, size int, ps *cutil.PageState) {
//line views/components/SVG.html:65
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:65
	StreamSVGInline(qw422016, k, size, ps)
//line views/components/SVG.html:65
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:65
}

//line views/components/SVG.html:65
func SVGInline(k string, size int, ps *cutil.PageState) string {
//line views/components/SVG.html:65
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:65
	WriteSVGInline(qb422016, k, size, ps)
//line views/components/SVG.html:65
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:65
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:65
	return qs422016
//line views/components/SVG.html:65
}

//line views/components/SVG.html:67
func StreamSVGLink(qw422016 *qt422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:68
	StreamSVGRef(qw422016, k, 18, 18, "link", ps)
//line views/components/SVG.html:69
}

//line views/components/SVG.html:69
func WriteSVGLink(qq422016 qtio422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:69
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:69
	StreamSVGLink(qw422016, k, ps)
//line views/components/SVG.html:69
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:69
}

//line views/components/SVG.html:69
func SVGLink(k string, ps *cutil.PageState) string {
//line views/components/SVG.html:69
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:69
	WriteSVGLink(qb422016, k, ps)
//line views/components/SVG.html:69
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:69
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:69
	return qs422016
//line views/components/SVG.html:69
}

//line views/components/SVG.html:71
func StreamSVGLinkPadded(qw422016 *qt422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:72
	StreamSVGRef(qw422016, k, 18, 18, "link padded", ps)
//line views/components/SVG.html:73
}

//line views/components/SVG.html:73
func WriteSVGLinkPadded(qq422016 qtio422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:73
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:73
	StreamSVGLinkPadded(qw422016, k, ps)
//line views/components/SVG.html:73
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:73
}

//line views/components/SVG.html:73
func SVGLinkPadded(k string, ps *cutil.PageState) string {
//line views/components/SVG.html:73
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:73
	WriteSVGLinkPadded(qb422016, k, ps)
//line views/components/SVG.html:73
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:73
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:73
	return qs422016
//line views/components/SVG.html:73
}

//line views/components/SVG.html:75
func StreamIconGallery(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/components/SVG.html:75
	qw422016.N().S(`  <div class="flex-wrap mt">
`)
//line views/components/SVG.html:77
	for _, k := range util.SVGIconKeys {
//line views/components/SVG.html:77
		qw422016.N().S(`    <div class="icon-gallery-icon">
      <div class="gallery-svg">`)
//line views/components/SVG.html:79
		StreamSVGRef(qw422016, k, 64, 64, "icon", ps)
//line views/components/SVG.html:79
		qw422016.N().S(`</div>
      <div class="gallery-title">`)
//line views/components/SVG.html:80
		qw422016.E().S(k)
//line views/components/SVG.html:80
		qw422016.N().S(`</div>
    </div>
`)
//line views/components/SVG.html:82
	}
//line views/components/SVG.html:82
	qw422016.N().S(`  </div>
`)
//line views/components/SVG.html:84
}

//line views/components/SVG.html:84
func WriteIconGallery(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/components/SVG.html:84
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:84
	StreamIconGallery(qw422016, as, ps)
//line views/components/SVG.html:84
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:84
}

//line views/components/SVG.html:84
func IconGallery(as *app.State, ps *cutil.PageState) string {
//line views/components/SVG.html:84
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:84
	WriteIconGallery(qb422016, as, ps)
//line views/components/SVG.html:84
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:84
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:84
	return qs422016
//line views/components/SVG.html:84
}

//line views/components/SVG.html:86
func StreamImage(qw422016 *qt422016.Writer, u string, w string, h string) {
//line views/components/SVG.html:87
	if u == "" {
//line views/components/SVG.html:87
		qw422016.N().S(`<em>no image</em>`)
//line views/components/SVG.html:89
	} else {
//line views/components/SVG.html:89
		qw422016.N().S(`<img style="max-width:`)
//line views/components/SVG.html:90
		qw422016.E().S(w)
//line views/components/SVG.html:90
		qw422016.N().S(`; max-height:`)
//line views/components/SVG.html:90
		qw422016.E().S(h)
//line views/components/SVG.html:90
		qw422016.N().S(`" src="`)
//line views/components/SVG.html:90
		qw422016.E().S(u)
//line views/components/SVG.html:90
		qw422016.N().S(`" />`)
//line views/components/SVG.html:91
	}
//line views/components/SVG.html:92
}

//line views/components/SVG.html:92
func WriteImage(qq422016 qtio422016.Writer, u string, w string, h string) {
//line views/components/SVG.html:92
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:92
	StreamImage(qw422016, u, w, h)
//line views/components/SVG.html:92
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:92
}

//line views/components/SVG.html:92
func Image(u string, w string, h string) string {
//line views/components/SVG.html:92
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:92
	WriteImage(qb422016, u, w, h)
//line views/components/SVG.html:92
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:92
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:92
	return qs422016
//line views/components/SVG.html:92
}
