// Code generated by qtc from "SVG.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/components/SVG.html:2
package components

//line views/components/SVG.html:2
import (
	"fmt"
	"strings"

	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/icons"
	"github.com/kyleu/pftest/app/util"
)

//line views/components/SVG.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/SVG.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/SVG.html:12
func StreamSVG(qw422016 *qt422016.Writer, k string) {
//line views/components/SVG.html:13
	if strings.HasPrefix(k, "brand-") {
//line views/components/SVG.html:14
		qw422016.N().S(icons.BrandLibrary().HTML(k))
//line views/components/SVG.html:15
	} else {
//line views/components/SVG.html:16
		if svg, ok := util.SVGLibrary[k]; ok {
//line views/components/SVG.html:17
			qw422016.N().S(svg)
//line views/components/SVG.html:18
		} else {
//line views/components/SVG.html:18
			qw422016.N().S(`<!-- missing icon definition for [`)
//line views/components/SVG.html:19
			qw422016.E().S(k)
//line views/components/SVG.html:19
			qw422016.N().S(`], using default icon -->`)
//line views/components/SVG.html:19
			qw422016.N().S(strings.ReplaceAll(util.SVGLibrary["question"], "-question", "-"+k))
//line views/components/SVG.html:20
		}
//line views/components/SVG.html:21
	}
//line views/components/SVG.html:22
}

//line views/components/SVG.html:22
func WriteSVG(qq422016 qtio422016.Writer, k string) {
//line views/components/SVG.html:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:22
	StreamSVG(qw422016, k)
//line views/components/SVG.html:22
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:22
}

//line views/components/SVG.html:22
func SVG(k string) string {
//line views/components/SVG.html:22
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:22
	WriteSVG(qb422016, k)
//line views/components/SVG.html:22
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:22
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:22
	return qs422016
//line views/components/SVG.html:22
}

//line views/components/SVG.html:24
func StreamSVGRef(qw422016 *qt422016.Writer, k string, w int, h int, cls string, ps *cutil.PageState) {
//line views/components/SVG.html:25
	if k != "" {
//line views/components/SVG.html:27
		ps.AddIcon(k)
		if w == 0 {
			w = 20
		}
		if h == 0 {
			h = 20
		}
		style := fmt.Sprintf("width: %dpx; height: %dpx;", w, h)

//line views/components/SVG.html:32
		if cls == "" {
//line views/components/SVG.html:32
			qw422016.N().S(`<svg style="`)
//line views/components/SVG.html:33
			qw422016.E().S(style)
//line views/components/SVG.html:33
			qw422016.N().S(`"><use xlink:href="#svg-`)
//line views/components/SVG.html:33
			qw422016.E().S(k)
//line views/components/SVG.html:33
			qw422016.N().S(`" /></svg>`)
//line views/components/SVG.html:34
		} else {
//line views/components/SVG.html:34
			qw422016.N().S(`<svg class="`)
//line views/components/SVG.html:35
			qw422016.E().S(cls)
//line views/components/SVG.html:35
			qw422016.N().S(`" style="`)
//line views/components/SVG.html:35
			qw422016.E().S(style)
//line views/components/SVG.html:35
			qw422016.N().S(`"><use xlink:href="#svg-`)
//line views/components/SVG.html:35
			qw422016.E().S(k)
//line views/components/SVG.html:35
			qw422016.N().S(`" /></svg>`)
//line views/components/SVG.html:36
		}
//line views/components/SVG.html:37
	}
//line views/components/SVG.html:38
}

//line views/components/SVG.html:38
func WriteSVGRef(qq422016 qtio422016.Writer, k string, w int, h int, cls string, ps *cutil.PageState) {
//line views/components/SVG.html:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:38
	StreamSVGRef(qw422016, k, w, h, cls, ps)
//line views/components/SVG.html:38
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:38
}

//line views/components/SVG.html:38
func SVGRef(k string, w int, h int, cls string, ps *cutil.PageState) string {
//line views/components/SVG.html:38
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:38
	WriteSVGRef(qb422016, k, w, h, cls, ps)
//line views/components/SVG.html:38
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:38
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:38
	return qs422016
//line views/components/SVG.html:38
}

//line views/components/SVG.html:40
func StreamIcon(qw422016 *qt422016.Writer, k string, size int, cls string, ps *cutil.PageState) {
//line views/components/SVG.html:41
	if strings.Contains(k, "/") {
//line views/components/SVG.html:41
		qw422016.N().S(`<img alt="SVG icon [`)
//line views/components/SVG.html:42
		qw422016.E().S(k)
//line views/components/SVG.html:42
		qw422016.N().S(`]" src="`)
//line views/components/SVG.html:42
		qw422016.E().S(k)
//line views/components/SVG.html:42
		qw422016.N().S(`" style="width:`)
//line views/components/SVG.html:42
		qw422016.N().D(size)
//line views/components/SVG.html:42
		qw422016.N().S(`px; height:`)
//line views/components/SVG.html:42
		qw422016.N().D(size)
//line views/components/SVG.html:42
		qw422016.N().S(`px;" />`)
//line views/components/SVG.html:43
	} else {
//line views/components/SVG.html:44
		StreamSVGRef(qw422016, k, size, size, cls, ps)
//line views/components/SVG.html:45
	}
//line views/components/SVG.html:46
}

//line views/components/SVG.html:46
func WriteIcon(qq422016 qtio422016.Writer, k string, size int, cls string, ps *cutil.PageState) {
//line views/components/SVG.html:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:46
	StreamIcon(qw422016, k, size, cls, ps)
//line views/components/SVG.html:46
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:46
}

//line views/components/SVG.html:46
func Icon(k string, size int, cls string, ps *cutil.PageState) string {
//line views/components/SVG.html:46
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:46
	WriteIcon(qb422016, k, size, cls, ps)
//line views/components/SVG.html:46
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:46
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:46
	return qs422016
//line views/components/SVG.html:46
}

//line views/components/SVG.html:48
func StreamSVGSimple(qw422016 *qt422016.Writer, k string, size int, ps *cutil.PageState) {
//line views/components/SVG.html:49
	StreamSVGRef(qw422016, k, size, size, "", ps)
//line views/components/SVG.html:50
}

//line views/components/SVG.html:50
func WriteSVGSimple(qq422016 qtio422016.Writer, k string, size int, ps *cutil.PageState) {
//line views/components/SVG.html:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:50
	StreamSVGSimple(qw422016, k, size, ps)
//line views/components/SVG.html:50
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:50
}

//line views/components/SVG.html:50
func SVGSimple(k string, size int, ps *cutil.PageState) string {
//line views/components/SVG.html:50
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:50
	WriteSVGSimple(qb422016, k, size, ps)
//line views/components/SVG.html:50
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:50
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:50
	return qs422016
//line views/components/SVG.html:50
}

//line views/components/SVG.html:52
func StreamSVGButton(qw422016 *qt422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:53
	StreamSVGRef(qw422016, k, 14, 14, "icon", ps)
//line views/components/SVG.html:54
}

//line views/components/SVG.html:54
func WriteSVGButton(qq422016 qtio422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:54
	StreamSVGButton(qw422016, k, ps)
//line views/components/SVG.html:54
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:54
}

//line views/components/SVG.html:54
func SVGButton(k string, ps *cutil.PageState) string {
//line views/components/SVG.html:54
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:54
	WriteSVGButton(qb422016, k, ps)
//line views/components/SVG.html:54
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:54
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:54
	return qs422016
//line views/components/SVG.html:54
}

//line views/components/SVG.html:56
func StreamSVGIcon(qw422016 *qt422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:57
	StreamSVGRef(qw422016, k, 18, 18, "icon", ps)
//line views/components/SVG.html:58
}

//line views/components/SVG.html:58
func WriteSVGIcon(qq422016 qtio422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:58
	StreamSVGIcon(qw422016, k, ps)
//line views/components/SVG.html:58
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:58
}

//line views/components/SVG.html:58
func SVGIcon(k string, ps *cutil.PageState) string {
//line views/components/SVG.html:58
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:58
	WriteSVGIcon(qb422016, k, ps)
//line views/components/SVG.html:58
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:58
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:58
	return qs422016
//line views/components/SVG.html:58
}

//line views/components/SVG.html:60
func StreamSVGBreadcrumb(qw422016 *qt422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:61
	StreamSVGRef(qw422016, k, 18, 18, "breadcrumb-icon", ps)
//line views/components/SVG.html:62
}

//line views/components/SVG.html:62
func WriteSVGBreadcrumb(qq422016 qtio422016.Writer, k string, ps *cutil.PageState) {
//line views/components/SVG.html:62
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:62
	StreamSVGBreadcrumb(qw422016, k, ps)
//line views/components/SVG.html:62
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:62
}

//line views/components/SVG.html:62
func SVGBreadcrumb(k string, ps *cutil.PageState) string {
//line views/components/SVG.html:62
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:62
	WriteSVGBreadcrumb(qb422016, k, ps)
//line views/components/SVG.html:62
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:62
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:62
	return qs422016
//line views/components/SVG.html:62
}

//line views/components/SVG.html:64
func StreamSVGInline(qw422016 *qt422016.Writer, k string, size int, ps *cutil.PageState) {
//line views/components/SVG.html:65
	StreamSVGRef(qw422016, k, size, size, "inline", ps)
//line views/components/SVG.html:66
}

//line views/components/SVG.html:66
func WriteSVGInline(qq422016 qtio422016.Writer, k string, size int, ps *cutil.PageState) {
//line views/components/SVG.html:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:66
	StreamSVGInline(qw422016, k, size, ps)
//line views/components/SVG.html:66
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:66
}

//line views/components/SVG.html:66
func SVGInline(k string, size int, ps *cutil.PageState) string {
//line views/components/SVG.html:66
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:66
	WriteSVGInline(qb422016, k, size, ps)
//line views/components/SVG.html:66
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:66
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:66
	return qs422016
//line views/components/SVG.html:66
}

//line views/components/SVG.html:68
func StreamIconGallery(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/components/SVG.html:68
	qw422016.N().S(`  <div class="flex-wrap mt">
`)
//line views/components/SVG.html:70
	for _, k := range util.SVGIconKeys {
//line views/components/SVG.html:70
		qw422016.N().S(`    <div class="icon-gallery-icon">
      <div class="gallery-svg">`)
//line views/components/SVG.html:72
		StreamSVGRef(qw422016, k, 64, 64, "icon", ps)
//line views/components/SVG.html:72
		qw422016.N().S(`</div>
      <div class="gallery-title">`)
//line views/components/SVG.html:73
		qw422016.E().S(k)
//line views/components/SVG.html:73
		qw422016.N().S(`</div>
    </div>
`)
//line views/components/SVG.html:75
	}
//line views/components/SVG.html:75
	qw422016.N().S(`  </div>
`)
//line views/components/SVG.html:77
}

//line views/components/SVG.html:77
func WriteIconGallery(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/components/SVG.html:77
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/SVG.html:77
	StreamIconGallery(qw422016, as, ps)
//line views/components/SVG.html:77
	qt422016.ReleaseWriter(qw422016)
//line views/components/SVG.html:77
}

//line views/components/SVG.html:77
func IconGallery(as *app.State, ps *cutil.PageState) string {
//line views/components/SVG.html:77
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/SVG.html:77
	WriteIconGallery(qb422016, as, ps)
//line views/components/SVG.html:77
	qs422016 := string(qb422016.B)
//line views/components/SVG.html:77
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/SVG.html:77
	return qs422016
//line views/components/SVG.html:77
}
