// Code generated by qtc from "Table.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vsoftdel/Table.html:1
package vsoftdel

//line views/vsoftdel/Table.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/app/softdel"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/view"
)

//line views/vsoftdel/Table.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vsoftdel/Table.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vsoftdel/Table.html:10
func StreamTableRow(qw422016 *qt422016.Writer, model *softdel.Softdel, ps *cutil.PageState, paths ...string) {
//line views/vsoftdel/Table.html:10
	qw422016.N().S(`
  <tr>
    <td><a href="`)
//line views/vsoftdel/Table.html:12
	qw422016.E().S(model.WebPath(paths...))
//line views/vsoftdel/Table.html:12
	qw422016.N().S(`">`)
//line views/vsoftdel/Table.html:12
	view.StreamString(qw422016, model.ID)
//line views/vsoftdel/Table.html:12
	qw422016.N().S(`</a></td>
    <td>`)
//line views/vsoftdel/Table.html:13
	view.StreamTimestamp(qw422016, &model.Created)
//line views/vsoftdel/Table.html:13
	qw422016.N().S(`</td>
    <td>`)
//line views/vsoftdel/Table.html:14
	view.StreamTimestamp(qw422016, model.Updated)
//line views/vsoftdel/Table.html:14
	qw422016.N().S(`</td>
    <td>`)
//line views/vsoftdel/Table.html:15
	view.StreamTimestamp(qw422016, model.Deleted)
//line views/vsoftdel/Table.html:15
	qw422016.N().S(`</td>
  </tr>
`)
//line views/vsoftdel/Table.html:17
}

//line views/vsoftdel/Table.html:17
func WriteTableRow(qq422016 qtio422016.Writer, model *softdel.Softdel, ps *cutil.PageState, paths ...string) {
//line views/vsoftdel/Table.html:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vsoftdel/Table.html:17
	StreamTableRow(qw422016, model, ps, paths...)
//line views/vsoftdel/Table.html:17
	qt422016.ReleaseWriter(qw422016)
//line views/vsoftdel/Table.html:17
}

//line views/vsoftdel/Table.html:17
func TableRow(model *softdel.Softdel, ps *cutil.PageState, paths ...string) string {
//line views/vsoftdel/Table.html:17
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vsoftdel/Table.html:17
	WriteTableRow(qb422016, model, ps, paths...)
//line views/vsoftdel/Table.html:17
	qs422016 := string(qb422016.B)
//line views/vsoftdel/Table.html:17
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vsoftdel/Table.html:17
	return qs422016
//line views/vsoftdel/Table.html:17
}

//line views/vsoftdel/Table.html:19
func StreamTable(qw422016 *qt422016.Writer, models softdel.Softdels, params filter.ParamSet, as *app.State, ps *cutil.PageState, paths ...string) {
//line views/vsoftdel/Table.html:19
	qw422016.N().S(`
`)
//line views/vsoftdel/Table.html:20
	prms := params.Sanitized("softdel", ps.Logger)

//line views/vsoftdel/Table.html:20
	qw422016.N().S(`  <div class="overflow clear">
    <table>
      <thead>
        <tr>
          `)
//line views/vsoftdel/Table.html:25
	components.StreamTableHeaderSimple(qw422016, "softdel", "id", "ID", "String text", prms, ps.URI, ps)
//line views/vsoftdel/Table.html:25
	qw422016.N().S(`
          `)
//line views/vsoftdel/Table.html:26
	components.StreamTableHeaderSimple(qw422016, "softdel", "created", "Created", "Date and time, in almost any format", prms, ps.URI, ps)
//line views/vsoftdel/Table.html:26
	qw422016.N().S(`
          `)
//line views/vsoftdel/Table.html:27
	components.StreamTableHeaderSimple(qw422016, "softdel", "updated", "Updated", "Date and time, in almost any format (optional)", prms, ps.URI, ps)
//line views/vsoftdel/Table.html:27
	qw422016.N().S(`
          `)
//line views/vsoftdel/Table.html:28
	components.StreamTableHeaderSimple(qw422016, "softdel", "deleted", "Deleted", "Date and time, in almost any format (optional)", prms, ps.URI, ps)
//line views/vsoftdel/Table.html:28
	qw422016.N().S(`
        </tr>
      </thead>
      <tbody>
`)
//line views/vsoftdel/Table.html:32
	for _, model := range models {
//line views/vsoftdel/Table.html:32
		qw422016.N().S(`        `)
//line views/vsoftdel/Table.html:33
		StreamTableRow(qw422016, model, ps, paths...)
//line views/vsoftdel/Table.html:34
	}
//line views/vsoftdel/Table.html:34
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vsoftdel/Table.html:38
	if prms.HasNextPage(len(models)+prms.Offset) || prms.HasPreviousPage() {
//line views/vsoftdel/Table.html:38
		qw422016.N().S(`  <hr />
  `)
//line views/vsoftdel/Table.html:40
		components.StreamPagination(qw422016, len(models)+prms.Offset, prms, ps.URI)
//line views/vsoftdel/Table.html:40
		qw422016.N().S(`
  <div class="clear"></div>
`)
//line views/vsoftdel/Table.html:42
	}
//line views/vsoftdel/Table.html:43
}

//line views/vsoftdel/Table.html:43
func WriteTable(qq422016 qtio422016.Writer, models softdel.Softdels, params filter.ParamSet, as *app.State, ps *cutil.PageState, paths ...string) {
//line views/vsoftdel/Table.html:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vsoftdel/Table.html:43
	StreamTable(qw422016, models, params, as, ps, paths...)
//line views/vsoftdel/Table.html:43
	qt422016.ReleaseWriter(qw422016)
//line views/vsoftdel/Table.html:43
}

//line views/vsoftdel/Table.html:43
func Table(models softdel.Softdels, params filter.ParamSet, as *app.State, ps *cutil.PageState, paths ...string) string {
//line views/vsoftdel/Table.html:43
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vsoftdel/Table.html:43
	WriteTable(qb422016, models, params, as, ps, paths...)
//line views/vsoftdel/Table.html:43
	qs422016 := string(qb422016.B)
//line views/vsoftdel/Table.html:43
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vsoftdel/Table.html:43
	return qs422016
//line views/vsoftdel/Table.html:43
}
