-- {% func DropAll() %}
-- {%= TroubleDrop() %}
-- {%= MixedCaseDrop() %}
-- {%= CapitalDrop() %}
-- {%= GroupDrop() %}
-- {%= SoftdelDrop() %}
-- {%= VersionDrop() %}
-- {%= TimestampDrop() %}
-- {%= BasicDrop() %}
-- {% endfunc %}

-- {% func CreateAll() %}
-- {%= BasicCreate() %}
-- {%= TimestampCreate() %}
-- {%= VersionCreate() %}
-- {%= SoftdelCreate() %}
-- {%= GroupCreate() %}
-- {%= CapitalCreate() %}
-- {%= MixedCaseCreate() %}
-- {%= TroubleCreate() %}
-- {% endfunc %}
