// Code generated by qtc from "audited.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/audited.sql:2
package ddl

//line queries/ddl/audited.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/audited.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/audited.sql:2
func StreamAuditedDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/audited.sql:2
	qw422016.N().S(`
drop table if exists "audited";
-- `)
//line queries/ddl/audited.sql:4
}

//line queries/ddl/audited.sql:4
func WriteAuditedDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/audited.sql:4
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/audited.sql:4
	StreamAuditedDrop(qw422016)
//line queries/ddl/audited.sql:4
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/audited.sql:4
}

//line queries/ddl/audited.sql:4
func AuditedDrop() string {
//line queries/ddl/audited.sql:4
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/audited.sql:4
	WriteAuditedDrop(qb422016)
//line queries/ddl/audited.sql:4
	qs422016 := string(qb422016.B)
//line queries/ddl/audited.sql:4
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/audited.sql:4
	return qs422016
//line queries/ddl/audited.sql:4
}

// --

//line queries/ddl/audited.sql:6
func StreamAuditedCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/audited.sql:6
	qw422016.N().S(`
create table if not exists "audited" (
  "id" uuid not null,
  "name" text not null,
  primary key ("id")
);
-- `)
//line queries/ddl/audited.sql:12
}

//line queries/ddl/audited.sql:12
func WriteAuditedCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/audited.sql:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/audited.sql:12
	StreamAuditedCreate(qw422016)
//line queries/ddl/audited.sql:12
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/audited.sql:12
}

//line queries/ddl/audited.sql:12
func AuditedCreate() string {
//line queries/ddl/audited.sql:12
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/audited.sql:12
	WriteAuditedCreate(qb422016)
//line queries/ddl/audited.sql:12
	qs422016 := string(qb422016.B)
//line queries/ddl/audited.sql:12
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/audited.sql:12
	return qs422016
//line queries/ddl/audited.sql:12
}
