// Code generated by qtc from "basic.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/basic.sql:2
package ddl

//line queries/ddl/basic.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/basic.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/basic.sql:2
func StreamBasicDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/basic.sql:2
	qw422016.N().S(`
drop table if exists "basic";
-- `)
//line queries/ddl/basic.sql:4
}

//line queries/ddl/basic.sql:4
func WriteBasicDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/basic.sql:4
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/basic.sql:4
	StreamBasicDrop(qw422016)
//line queries/ddl/basic.sql:4
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/basic.sql:4
}

//line queries/ddl/basic.sql:4
func BasicDrop() string {
//line queries/ddl/basic.sql:4
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/basic.sql:4
	WriteBasicDrop(qb422016)
//line queries/ddl/basic.sql:4
	qs422016 := string(qb422016.B)
//line queries/ddl/basic.sql:4
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/basic.sql:4
	return qs422016
//line queries/ddl/basic.sql:4
}

// --

//line queries/ddl/basic.sql:6
func StreamBasicCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/basic.sql:6
	qw422016.N().S(`
create table if not exists "basic" (
  "id" uuid not null,
  "name" text not null,
  "status" text not null,
  "created" timestamp not null default now(),
  primary key ("id")
);
-- `)
//line queries/ddl/basic.sql:14
}

//line queries/ddl/basic.sql:14
func WriteBasicCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/basic.sql:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/basic.sql:14
	StreamBasicCreate(qw422016)
//line queries/ddl/basic.sql:14
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/basic.sql:14
}

//line queries/ddl/basic.sql:14
func BasicCreate() string {
//line queries/ddl/basic.sql:14
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/basic.sql:14
	WriteBasicCreate(qb422016)
//line queries/ddl/basic.sql:14
	qs422016 := string(qb422016.B)
//line queries/ddl/basic.sql:14
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/basic.sql:14
	return qs422016
//line queries/ddl/basic.sql:14
}
