// Code generated by qtc from "Capital.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/Capital.sql:2
package ddl

//line queries/ddl/Capital.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/Capital.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/Capital.sql:2
func StreamCapitalDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/Capital.sql:2
	qw422016.N().S(`
drop table if exists "Capital";
-- `)
//line queries/ddl/Capital.sql:4
}

//line queries/ddl/Capital.sql:4
func WriteCapitalDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/Capital.sql:4
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/Capital.sql:4
	StreamCapitalDrop(qw422016)
//line queries/ddl/Capital.sql:4
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/Capital.sql:4
}

//line queries/ddl/Capital.sql:4
func CapitalDrop() string {
//line queries/ddl/Capital.sql:4
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/Capital.sql:4
	WriteCapitalDrop(qb422016)
//line queries/ddl/Capital.sql:4
	qs422016 := string(qb422016.B)
//line queries/ddl/Capital.sql:4
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/Capital.sql:4
	return qs422016
//line queries/ddl/Capital.sql:4
}

// --

//line queries/ddl/Capital.sql:6
func StreamCapitalCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/Capital.sql:6
	qw422016.N().S(`
create table if not exists "Capital" (
  "ID" text not null,
  "Name" text not null,
  "Birthday" timestamp not null,
  "Deathday" timestamp,
  primary key ("ID")
);
-- `)
//line queries/ddl/Capital.sql:14
}

//line queries/ddl/Capital.sql:14
func WriteCapitalCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/Capital.sql:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/Capital.sql:14
	StreamCapitalCreate(qw422016)
//line queries/ddl/Capital.sql:14
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/Capital.sql:14
}

//line queries/ddl/Capital.sql:14
func CapitalCreate() string {
//line queries/ddl/Capital.sql:14
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/Capital.sql:14
	WriteCapitalCreate(qb422016)
//line queries/ddl/Capital.sql:14
	qs422016 := string(qb422016.B)
//line queries/ddl/Capital.sql:14
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/Capital.sql:14
	return qs422016
//line queries/ddl/Capital.sql:14
}
