// Code generated by qtc from "Capital.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/Capital.sql:2
package ddl

//line queries/ddl/Capital.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/Capital.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/Capital.sql:2
func StreamCapitalDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/Capital.sql:2
	qw422016.N().S(`
drop table if exists "Capital_Version";
drop table if exists "Capital";
-- `)
//line queries/ddl/Capital.sql:5
}

//line queries/ddl/Capital.sql:5
func WriteCapitalDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/Capital.sql:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/Capital.sql:5
	StreamCapitalDrop(qw422016)
//line queries/ddl/Capital.sql:5
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/Capital.sql:5
}

//line queries/ddl/Capital.sql:5
func CapitalDrop() string {
//line queries/ddl/Capital.sql:5
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/Capital.sql:5
	WriteCapitalDrop(qb422016)
//line queries/ddl/Capital.sql:5
	qs422016 := string(qb422016.B)
//line queries/ddl/Capital.sql:5
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/Capital.sql:5
	return qs422016
//line queries/ddl/Capital.sql:5
}

// --

//line queries/ddl/Capital.sql:7
func StreamCapitalCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/Capital.sql:7
	qw422016.N().S(`
create table if not exists "Capital" (
  "ID" text not null,
  "current_Version" int not null default 1,
  primary key ("ID")
);

create table if not exists "Capital_Version" (
  "Capital_ID" text not null,
  "Version" int not null default 1,
  "Name" text not null,
  "Birthday" timestamp not null,
  "Deathday" timestamp,
  foreign key ("Capital_ID") references "Capital" ("ID"),
  primary key ("Capital_ID", "Version")
);

create index if not exists "Capital_Version__Capital_ID_idx" on "Capital_Version" ("Capital_ID");
-- `)
//line queries/ddl/Capital.sql:25
}

//line queries/ddl/Capital.sql:25
func WriteCapitalCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/Capital.sql:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/Capital.sql:25
	StreamCapitalCreate(qw422016)
//line queries/ddl/Capital.sql:25
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/Capital.sql:25
}

//line queries/ddl/Capital.sql:25
func CapitalCreate() string {
//line queries/ddl/Capital.sql:25
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/Capital.sql:25
	WriteCapitalCreate(qb422016)
//line queries/ddl/Capital.sql:25
	qs422016 := string(qb422016.B)
//line queries/ddl/Capital.sql:25
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/Capital.sql:25
	return qs422016
//line queries/ddl/Capital.sql:25
}
