// Code generated by qtc from "reference.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/ddl/reference.sql:1
package ddl

//line queries/ddl/reference.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/reference.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/reference.sql:1
func StreamReferenceDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/reference.sql:1
	qw422016.N().S(`
drop table if exists "reference";
-- `)
//line queries/ddl/reference.sql:3
}

//line queries/ddl/reference.sql:3
func WriteReferenceDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/reference.sql:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/reference.sql:3
	StreamReferenceDrop(qw422016)
//line queries/ddl/reference.sql:3
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/reference.sql:3
}

//line queries/ddl/reference.sql:3
func ReferenceDrop() string {
//line queries/ddl/reference.sql:3
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/reference.sql:3
	WriteReferenceDrop(qb422016)
//line queries/ddl/reference.sql:3
	qs422016 := string(qb422016.B)
//line queries/ddl/reference.sql:3
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/reference.sql:3
	return qs422016
//line queries/ddl/reference.sql:3
}

// --

//line queries/ddl/reference.sql:5
func StreamReferenceCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/reference.sql:5
	qw422016.N().S(`
create table if not exists "reference" (
  "id" uuid not null,
  "custom" jsonb not null,
  "self" jsonb not null,
  "created" timestamp not null default now(),
  primary key ("id")
);
-- `)
//line queries/ddl/reference.sql:13
}

//line queries/ddl/reference.sql:13
func WriteReferenceCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/reference.sql:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/reference.sql:13
	StreamReferenceCreate(qw422016)
//line queries/ddl/reference.sql:13
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/reference.sql:13
}

//line queries/ddl/reference.sql:13
func ReferenceCreate() string {
//line queries/ddl/reference.sql:13
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/reference.sql:13
	WriteReferenceCreate(qb422016)
//line queries/ddl/reference.sql:13
	qs422016 := string(qb422016.B)
//line queries/ddl/reference.sql:13
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/reference.sql:13
	return qs422016
//line queries/ddl/reference.sql:13
}
