// Code generated by qtc from "relation.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/relation.sql:2
package ddl

//line queries/ddl/relation.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/relation.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/relation.sql:2
func StreamRelationDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/relation.sql:2
	qw422016.N().S(`
drop table if exists "relation";
-- `)
//line queries/ddl/relation.sql:4
}

//line queries/ddl/relation.sql:4
func WriteRelationDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/relation.sql:4
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/relation.sql:4
	StreamRelationDrop(qw422016)
//line queries/ddl/relation.sql:4
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/relation.sql:4
}

//line queries/ddl/relation.sql:4
func RelationDrop() string {
//line queries/ddl/relation.sql:4
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/relation.sql:4
	WriteRelationDrop(qb422016)
//line queries/ddl/relation.sql:4
	qs422016 := string(qb422016.B)
//line queries/ddl/relation.sql:4
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/relation.sql:4
	return qs422016
//line queries/ddl/relation.sql:4
}

// --

//line queries/ddl/relation.sql:6
func StreamRelationCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/relation.sql:6
	qw422016.N().S(`
create table if not exists "relation" (
  "id" uuid not null,
  "basic_id" uuid not null,
  "name" text not null,
  "created" timestamp not null default now(),
  foreign key ("basic_id") references "basic" ("id"),
  primary key ("id")
);

create index if not exists "relation__basic_id_idx" on "relation" ("basic_id");
-- `)
//line queries/ddl/relation.sql:17
}

//line queries/ddl/relation.sql:17
func WriteRelationCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/relation.sql:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/relation.sql:17
	StreamRelationCreate(qw422016)
//line queries/ddl/relation.sql:17
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/relation.sql:17
}

//line queries/ddl/relation.sql:17
func RelationCreate() string {
//line queries/ddl/relation.sql:17
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/relation.sql:17
	WriteRelationCreate(qb422016)
//line queries/ddl/relation.sql:17
	qs422016 := string(qb422016.B)
//line queries/ddl/relation.sql:17
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/relation.sql:17
	return qs422016
//line queries/ddl/relation.sql:17
}
