// Code generated by qtc from "seed.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/seed.sql:2
package ddl

//line queries/ddl/seed.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/seed.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/seed.sql:2
func StreamSeedDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/seed.sql:2
	qw422016.N().S(`
drop table if exists "seed";
-- `)
//line queries/ddl/seed.sql:4
}

//line queries/ddl/seed.sql:4
func WriteSeedDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/seed.sql:4
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/seed.sql:4
	StreamSeedDrop(qw422016)
//line queries/ddl/seed.sql:4
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/seed.sql:4
}

//line queries/ddl/seed.sql:4
func SeedDrop() string {
//line queries/ddl/seed.sql:4
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/seed.sql:4
	WriteSeedDrop(qb422016)
//line queries/ddl/seed.sql:4
	qs422016 := string(qb422016.B)
//line queries/ddl/seed.sql:4
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/seed.sql:4
	return qs422016
//line queries/ddl/seed.sql:4
}

// --

//line queries/ddl/seed.sql:6
func StreamSeedCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/seed.sql:6
	qw422016.N().S(`
create table if not exists "seed" (
  "id" uuid not null,
  "name" text not null,
  "size" int not null,
  "obj" jsonb not null,
  primary key ("id")
);
-- `)
//line queries/ddl/seed.sql:14
}

//line queries/ddl/seed.sql:14
func WriteSeedCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/seed.sql:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/seed.sql:14
	StreamSeedCreate(qw422016)
//line queries/ddl/seed.sql:14
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/seed.sql:14
}

//line queries/ddl/seed.sql:14
func SeedCreate() string {
//line queries/ddl/seed.sql:14
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/seed.sql:14
	WriteSeedCreate(qb422016)
//line queries/ddl/seed.sql:14
	qs422016 := string(qb422016.B)
//line queries/ddl/seed.sql:14
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/seed.sql:14
	return qs422016
//line queries/ddl/seed.sql:14
}
