// Code generated by qtc from "seed.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/ddl/seed.sql:1
package ddl

//line queries/ddl/seed.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/seed.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/seed.sql:1
func StreamSeedDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/seed.sql:1
	qw422016.N().S(`
drop table if exists "seed";
-- `)
//line queries/ddl/seed.sql:3
}

//line queries/ddl/seed.sql:3
func WriteSeedDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/seed.sql:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/seed.sql:3
	StreamSeedDrop(qw422016)
//line queries/ddl/seed.sql:3
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/seed.sql:3
}

//line queries/ddl/seed.sql:3
func SeedDrop() string {
//line queries/ddl/seed.sql:3
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/seed.sql:3
	WriteSeedDrop(qb422016)
//line queries/ddl/seed.sql:3
	qs422016 := string(qb422016.B)
//line queries/ddl/seed.sql:3
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/seed.sql:3
	return qs422016
//line queries/ddl/seed.sql:3
}

// --

//line queries/ddl/seed.sql:5
func StreamSeedCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/seed.sql:5
	qw422016.N().S(`
create table if not exists "seed" (
  "id" uuid not null,
  "name" text not null,
  "size" int not null,
  "obj" jsonb not null,
  primary key ("id")
);
-- `)
//line queries/ddl/seed.sql:13
}

//line queries/ddl/seed.sql:13
func WriteSeedCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/seed.sql:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/seed.sql:13
	StreamSeedCreate(qw422016)
//line queries/ddl/seed.sql:13
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/seed.sql:13
}

//line queries/ddl/seed.sql:13
func SeedCreate() string {
//line queries/ddl/seed.sql:13
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/seed.sql:13
	WriteSeedCreate(qb422016)
//line queries/ddl/seed.sql:13
	qs422016 := string(qb422016.B)
//line queries/ddl/seed.sql:13
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/seed.sql:13
	return qs422016
//line queries/ddl/seed.sql:13
}
