// Code generated by qtc from "timestamp.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/timestamp.sql:2
package ddl

//line queries/ddl/timestamp.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/timestamp.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/timestamp.sql:2
func StreamTimestampDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/timestamp.sql:2
	qw422016.N().S(`
drop table if exists "timestamp";
-- `)
//line queries/ddl/timestamp.sql:4
}

//line queries/ddl/timestamp.sql:4
func WriteTimestampDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/timestamp.sql:4
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/timestamp.sql:4
	StreamTimestampDrop(qw422016)
//line queries/ddl/timestamp.sql:4
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/timestamp.sql:4
}

//line queries/ddl/timestamp.sql:4
func TimestampDrop() string {
//line queries/ddl/timestamp.sql:4
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/timestamp.sql:4
	WriteTimestampDrop(qb422016)
//line queries/ddl/timestamp.sql:4
	qs422016 := string(qb422016.B)
//line queries/ddl/timestamp.sql:4
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/timestamp.sql:4
	return qs422016
//line queries/ddl/timestamp.sql:4
}

// --

//line queries/ddl/timestamp.sql:6
func StreamTimestampCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/timestamp.sql:6
	qw422016.N().S(`
create table if not exists "timestamp" (
  "id" text not null,
  "created" timestamp not null default now(),
  "updated" timestamp default now(),
  "deleted" timestamp default now(),
  primary key ("id")
);
-- `)
//line queries/ddl/timestamp.sql:14
}

//line queries/ddl/timestamp.sql:14
func WriteTimestampCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/timestamp.sql:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/timestamp.sql:14
	StreamTimestampCreate(qw422016)
//line queries/ddl/timestamp.sql:14
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/timestamp.sql:14
}

//line queries/ddl/timestamp.sql:14
func TimestampCreate() string {
//line queries/ddl/timestamp.sql:14
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/timestamp.sql:14
	WriteTimestampCreate(qb422016)
//line queries/ddl/timestamp.sql:14
	qs422016 := string(qb422016.B)
//line queries/ddl/timestamp.sql:14
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/timestamp.sql:14
	return qs422016
//line queries/ddl/timestamp.sql:14
}
