// Code generated by qtc from "Edit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vtimestamp/Edit.html:2
package vtimestamp

//line views/vtimestamp/Edit.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/timestamp"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/edit"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vtimestamp/Edit.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vtimestamp/Edit.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vtimestamp/Edit.html:11
type Edit struct {
	layout.Basic
	Model *timestamp.Timestamp
	IsNew bool
}

//line views/vtimestamp/Edit.html:17
func (p *Edit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtimestamp/Edit.html:17
	qw422016.N().S(`
  <div class="card">
`)
//line views/vtimestamp/Edit.html:19
	if p.IsNew {
//line views/vtimestamp/Edit.html:19
		qw422016.N().S(`    <div class="right"><a href="?prototype=random"><button>Random</button></a></div>
    <h3>`)
//line views/vtimestamp/Edit.html:21
		components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vtimestamp/Edit.html:21
		qw422016.N().S(` New Timestamp</h3>
    <form action="/timestamp/_new" class="mt" method="post">
`)
//line views/vtimestamp/Edit.html:23
	} else {
//line views/vtimestamp/Edit.html:23
		qw422016.N().S(`    <div class="right"><a href="`)
//line views/vtimestamp/Edit.html:24
		qw422016.E().S(p.Model.WebPath())
//line views/vtimestamp/Edit.html:24
		qw422016.N().S(`/delete" onclick="return confirm('Are you sure you wish to delete timestamp [`)
//line views/vtimestamp/Edit.html:24
		qw422016.E().S(p.Model.String())
//line views/vtimestamp/Edit.html:24
		qw422016.N().S(`]?')"><button>Delete</button></a></div>
    <h3>`)
//line views/vtimestamp/Edit.html:25
		components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vtimestamp/Edit.html:25
		qw422016.N().S(` Edit Timestamp [`)
//line views/vtimestamp/Edit.html:25
		qw422016.E().S(p.Model.String())
//line views/vtimestamp/Edit.html:25
		qw422016.N().S(`]</h3>
    <form action="" method="post">
`)
//line views/vtimestamp/Edit.html:27
	}
//line views/vtimestamp/Edit.html:27
	qw422016.N().S(`      <table class="mt expanded">
        <tbody>
          `)
//line views/vtimestamp/Edit.html:30
	if p.IsNew {
//line views/vtimestamp/Edit.html:30
		edit.StreamStringTable(qw422016, "id", "", "ID", p.Model.ID, 5, "String text")
//line views/vtimestamp/Edit.html:30
	}
//line views/vtimestamp/Edit.html:30
	qw422016.N().S(`
          `)
//line views/vtimestamp/Edit.html:31
	edit.StreamTimestampTable(qw422016, "deleted", "", "Deleted", p.Model.Deleted, 5, "Date and time, in almost any format (optional)")
//line views/vtimestamp/Edit.html:31
	qw422016.N().S(`
          <tr><td colspan="2"><button type="submit">Save Changes</button></td></tr>
        </tbody>
      </table>
    </form>
  </div>
`)
//line views/vtimestamp/Edit.html:37
}

//line views/vtimestamp/Edit.html:37
func (p *Edit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtimestamp/Edit.html:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vtimestamp/Edit.html:37
	p.StreamBody(qw422016, as, ps)
//line views/vtimestamp/Edit.html:37
	qt422016.ReleaseWriter(qw422016)
//line views/vtimestamp/Edit.html:37
}

//line views/vtimestamp/Edit.html:37
func (p *Edit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vtimestamp/Edit.html:37
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vtimestamp/Edit.html:37
	p.WriteBody(qb422016, as, ps)
//line views/vtimestamp/Edit.html:37
	qs422016 := string(qb422016.B)
//line views/vtimestamp/Edit.html:37
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vtimestamp/Edit.html:37
	return qs422016
//line views/vtimestamp/Edit.html:37
}
