// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vrelation/Detail.html:2
package vrelation

//line views/vrelation/Detail.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/basic"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/relation"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vrelation/Detail.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vrelation/Detail.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vrelation/Detail.html:11
type Detail struct {
	layout.Basic
	Model          *relation.Relation
	BasicByBasicID *basic.Basic
}

//line views/vrelation/Detail.html:17
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vrelation/Detail.html:17
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-relation"><button type="button">JSON</button></a>
      <a href="`)
//line views/vrelation/Detail.html:21
	qw422016.E().S(p.Model.WebPath())
//line views/vrelation/Detail.html:21
	qw422016.N().S(`/edit"><button>`)
//line views/vrelation/Detail.html:21
	components.StreamSVGRef(qw422016, "edit", 15, 15, "icon", ps)
//line views/vrelation/Detail.html:21
	qw422016.N().S(`Edit</button></a>
    </div>
    <h3>`)
//line views/vrelation/Detail.html:23
	components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vrelation/Detail.html:23
	qw422016.N().S(` `)
//line views/vrelation/Detail.html:23
	qw422016.E().S(p.Model.TitleString())
//line views/vrelation/Detail.html:23
	qw422016.N().S(`</h3>
    <div><a href="/relation"><em>Relation</em></a></div>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
          <td>`)
//line views/vrelation/Detail.html:29
	components.StreamDisplayUUID(qw422016, &p.Model.ID)
//line views/vrelation/Detail.html:29
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">Basic ID</th>
          <td class="nowrap">
            `)
//line views/vrelation/Detail.html:34
	components.StreamDisplayUUID(qw422016, &p.Model.BasicID)
//line views/vrelation/Detail.html:34
	if p.BasicByBasicID != nil {
//line views/vrelation/Detail.html:34
		qw422016.N().S(` (`)
//line views/vrelation/Detail.html:34
		qw422016.E().S(p.BasicByBasicID.TitleString())
//line views/vrelation/Detail.html:34
		qw422016.N().S(`)`)
//line views/vrelation/Detail.html:34
	}
//line views/vrelation/Detail.html:34
	qw422016.N().S(`
            <a title="Basic" href="`)
//line views/vrelation/Detail.html:35
	qw422016.E().S(`/basic` + `/` + p.Model.BasicID.String())
//line views/vrelation/Detail.html:35
	qw422016.N().S(`">`)
//line views/vrelation/Detail.html:35
	components.StreamSVGRef(qw422016, "star", 18, 18, "", ps)
//line views/vrelation/Detail.html:35
	qw422016.N().S(`</a>
          </td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Name</th>
          <td><strong>`)
//line views/vrelation/Detail.html:40
	qw422016.E().S(p.Model.Name)
//line views/vrelation/Detail.html:40
	qw422016.N().S(`</strong></td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Created</th>
          <td>`)
//line views/vrelation/Detail.html:44
	components.StreamDisplayTimestamp(qw422016, &p.Model.Created)
//line views/vrelation/Detail.html:44
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vrelation/Detail.html:50
	qw422016.N().S(`  `)
//line views/vrelation/Detail.html:51
	components.StreamJSONModal(qw422016, "relation", "Relation JSON", p.Model, 1)
//line views/vrelation/Detail.html:51
	qw422016.N().S(`
`)
//line views/vrelation/Detail.html:52
}

//line views/vrelation/Detail.html:52
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vrelation/Detail.html:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vrelation/Detail.html:52
	p.StreamBody(qw422016, as, ps)
//line views/vrelation/Detail.html:52
	qt422016.ReleaseWriter(qw422016)
//line views/vrelation/Detail.html:52
}

//line views/vrelation/Detail.html:52
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vrelation/Detail.html:52
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vrelation/Detail.html:52
	p.WriteBody(qb422016, as, ps)
//line views/vrelation/Detail.html:52
	qs422016 := string(qb422016.B)
//line views/vrelation/Detail.html:52
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vrelation/Detail.html:52
	return qs422016
//line views/vrelation/Detail.html:52
}
