// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vrelation/List.html:2
package vrelation

//line views/vrelation/List.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/basic"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/app/relation"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vrelation/List.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vrelation/List.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vrelation/List.html:12
type List struct {
	layout.Basic
	Models relation.Relations
	Basics basic.Basics
	Params filter.ParamSet
}

//line views/vrelation/List.html:19
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vrelation/List.html:19
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="/relation/new"><button>New</button></a></div>
    <h3>`)
//line views/vrelation/List.html:22
	components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vrelation/List.html:22
	qw422016.N().S(` Relations</h3>
`)
//line views/vrelation/List.html:23
	if len(p.Models) == 0 {
//line views/vrelation/List.html:23
		qw422016.N().S(`    <div class="mt"><em>No relations available</em></div>
`)
//line views/vrelation/List.html:25
	} else {
//line views/vrelation/List.html:25
		qw422016.N().S(`    `)
//line views/vrelation/List.html:26
		StreamTable(qw422016, p.Models, p.Basics, p.Params, as, ps)
//line views/vrelation/List.html:26
		qw422016.N().S(`
`)
//line views/vrelation/List.html:27
	}
//line views/vrelation/List.html:27
	qw422016.N().S(`  </div>
`)
//line views/vrelation/List.html:29
}

//line views/vrelation/List.html:29
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vrelation/List.html:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vrelation/List.html:29
	p.StreamBody(qw422016, as, ps)
//line views/vrelation/List.html:29
	qt422016.ReleaseWriter(qw422016)
//line views/vrelation/List.html:29
}

//line views/vrelation/List.html:29
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vrelation/List.html:29
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vrelation/List.html:29
	p.WriteBody(qb422016, as, ps)
//line views/vrelation/List.html:29
	qs422016 := string(qb422016.B)
//line views/vrelation/List.html:29
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vrelation/List.html:29
	return qs422016
//line views/vrelation/List.html:29
}
