// Package routes - Content managed by Project Forge, see [projectforge.md] for details.
package routes

import (
	"github.com/fasthttp/router"

	"github.com/kyleu/pftest/app/controller"
	"github.com/kyleu/pftest/app/controller/cg1/cg2"
)

func generatedRoutes(r *router.Router) {
	r.GET("/capital", controller.CapitalList)
	r.GET("/capital/random", controller.CapitalCreateFormRandom)
	r.GET("/capital/new", controller.CapitalCreateForm)
	r.POST("/capital/new", controller.CapitalCreate)
	r.GET("/capital/{id}", controller.CapitalDetail)
	r.GET("/capital/{id}/edit", controller.CapitalEditForm)
	r.POST("/capital/{id}/edit", controller.CapitalEdit)
	r.GET("/capital/{id}/delete", controller.CapitalDelete)
	r.GET("/audited", controller.AuditedList)
	r.GET("/audited/random", controller.AuditedCreateFormRandom)
	r.GET("/audited/new", controller.AuditedCreateForm)
	r.POST("/audited/new", controller.AuditedCreate)
	r.GET("/audited/{id}", controller.AuditedDetail)
	r.GET("/audited/{id}/edit", controller.AuditedEditForm)
	r.POST("/audited/{id}/edit", controller.AuditedEdit)
	r.GET("/audited/{id}/delete", controller.AuditedDelete)
	r.GET("/basic", controller.BasicList)
	r.GET("/basic/random", controller.BasicCreateFormRandom)
	r.GET("/basic/new", controller.BasicCreateForm)
	r.POST("/basic/new", controller.BasicCreate)
	r.GET("/basic/{id}", controller.BasicDetail)
	r.GET("/basic/{id}/edit", controller.BasicEditForm)
	r.POST("/basic/{id}/edit", controller.BasicEdit)
	r.GET("/basic/{id}/delete", controller.BasicDelete)
	r.GET("/mixedcase", controller.MixedCaseList)
	r.GET("/mixedcase/random", controller.MixedCaseCreateFormRandom)
	r.GET("/mixedcase/new", controller.MixedCaseCreateForm)
	r.POST("/mixedcase/new", controller.MixedCaseCreate)
	r.GET("/mixedcase/{id}", controller.MixedCaseDetail)
	r.GET("/mixedcase/{id}/edit", controller.MixedCaseEditForm)
	r.POST("/mixedcase/{id}/edit", controller.MixedCaseEdit)
	r.GET("/mixedcase/{id}/delete", controller.MixedCaseDelete)
	r.GET("/g1/g2/path", cg2.PathList)
	r.GET("/g1/g2/path/random", cg2.PathCreateFormRandom)
	r.GET("/g1/g2/path/new", cg2.PathCreateForm)
	r.POST("/g1/g2/path/new", cg2.PathCreate)
	r.GET("/g1/g2/path/{id}", cg2.PathDetail)
	r.GET("/g1/g2/path/{id}/edit", cg2.PathEditForm)
	r.POST("/g1/g2/path/{id}/edit", cg2.PathEdit)
	r.GET("/g1/g2/path/{id}/delete", cg2.PathDelete)
	r.GET("/reference", controller.ReferenceList)
	r.GET("/reference/random", controller.ReferenceCreateFormRandom)
	r.GET("/reference/new", controller.ReferenceCreateForm)
	r.POST("/reference/new", controller.ReferenceCreate)
	r.GET("/reference/{id}", controller.ReferenceDetail)
	r.GET("/reference/{id}/edit", controller.ReferenceEditForm)
	r.POST("/reference/{id}/edit", controller.ReferenceEdit)
	r.GET("/reference/{id}/delete", controller.ReferenceDelete)
	r.GET("/relation", controller.RelationList)
	r.GET("/relation/random", controller.RelationCreateFormRandom)
	r.GET("/relation/new", controller.RelationCreateForm)
	r.POST("/relation/new", controller.RelationCreate)
	r.GET("/relation/{id}", controller.RelationDetail)
	r.GET("/relation/{id}/edit", controller.RelationEditForm)
	r.POST("/relation/{id}/edit", controller.RelationEdit)
	r.GET("/relation/{id}/delete", controller.RelationDelete)
	r.GET("/seed", controller.SeedList)
	r.GET("/seed/random", controller.SeedCreateFormRandom)
	r.GET("/seed/new", controller.SeedCreateForm)
	r.POST("/seed/new", controller.SeedCreate)
	r.GET("/seed/{id}", controller.SeedDetail)
	r.GET("/seed/{id}/edit", controller.SeedEditForm)
	r.POST("/seed/{id}/edit", controller.SeedEdit)
	r.GET("/seed/{id}/delete", controller.SeedDelete)
	r.GET("/softdel", controller.SoftdelList)
	r.GET("/softdel/random", controller.SoftdelCreateFormRandom)
	r.GET("/softdel/new", controller.SoftdelCreateForm)
	r.POST("/softdel/new", controller.SoftdelCreate)
	r.GET("/softdel/{id}", controller.SoftdelDetail)
	r.GET("/softdel/{id}/edit", controller.SoftdelEditForm)
	r.POST("/softdel/{id}/edit", controller.SoftdelEdit)
	r.GET("/softdel/{id}/delete", controller.SoftdelDelete)
	r.GET("/timestamp", controller.TimestampList)
	r.GET("/timestamp/random", controller.TimestampCreateFormRandom)
	r.GET("/timestamp/new", controller.TimestampCreateForm)
	r.POST("/timestamp/new", controller.TimestampCreate)
	r.GET("/timestamp/{id}", controller.TimestampDetail)
	r.GET("/timestamp/{id}/edit", controller.TimestampEditForm)
	r.POST("/timestamp/{id}/edit", controller.TimestampEdit)
	r.GET("/timestamp/{id}/delete", controller.TimestampDelete)
	r.GET("/troub/le", controller.TroubleList)
	r.GET("/troub/le/random", controller.TroubleCreateFormRandom)
	r.GET("/troub/le/new", controller.TroubleCreateForm)
	r.POST("/troub/le/new", controller.TroubleCreate)
	r.GET("/troub/le/{from}/{where}", controller.TroubleDetail)
	r.GET("/troub/le/{from}/{where}/edit", controller.TroubleEditForm)
	r.POST("/troub/le/{from}/{where}/edit", controller.TroubleEdit)
	r.GET("/troub/le/{from}/{where}/delete", controller.TroubleDelete)
}
