// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vversion/Detail.html:2
package vversion

//line views/vversion/Detail.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/app/version"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vversion/Detail.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vversion/Detail.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vversion/Detail.html:11
type Detail struct {
	layout.Basic
	Model     *version.Version
	Params    filter.ParamSet
	Revisions version.Versions
}

//line views/vversion/Detail.html:18
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vversion/Detail.html:18
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-version"><button type="button">JSON</button></a>
      <a href="`)
//line views/vversion/Detail.html:22
	qw422016.E().S(p.Model.WebPath())
//line views/vversion/Detail.html:22
	qw422016.N().S(`/edit"><button>`)
//line views/vversion/Detail.html:22
	components.StreamSVGRef(qw422016, "edit", 15, 15, "icon", ps)
//line views/vversion/Detail.html:22
	qw422016.N().S(`Edit</button></a>
    </div>
    <h3>`)
//line views/vversion/Detail.html:24
	components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vversion/Detail.html:24
	qw422016.N().S(` `)
//line views/vversion/Detail.html:24
	qw422016.E().S(p.Model.TitleString())
//line views/vversion/Detail.html:24
	qw422016.N().S(`</h3>
    <div><a href="/version"><em>Version</em></a></div>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="String text">ID</th>
          <td>`)
//line views/vversion/Detail.html:30
	qw422016.E().S(p.Model.ID)
//line views/vversion/Detail.html:30
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Integer">Revision</th>
          <td>`)
//line views/vversion/Detail.html:34
	qw422016.N().D(p.Model.Revision)
//line views/vversion/Detail.html:34
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Constcol</th>
          <td>`)
//line views/vversion/Detail.html:38
	qw422016.E().S(p.Model.Constcol)
//line views/vversion/Detail.html:38
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="JSON object">Varcol</th>
          <td>`)
//line views/vversion/Detail.html:42
	components.StreamJSON(qw422016, p.Model.Varcol)
//line views/vversion/Detail.html:42
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Created</th>
          <td>`)
//line views/vversion/Detail.html:46
	components.StreamDisplayTimestamp(qw422016, &p.Model.Created)
//line views/vversion/Detail.html:46
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format (optional)">Updated</th>
          <td>`)
//line views/vversion/Detail.html:50
	components.StreamDisplayTimestamp(qw422016, p.Model.Updated)
//line views/vversion/Detail.html:50
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vversion/Detail.html:55
	if len(p.Revisions) > 1 {
//line views/vversion/Detail.html:55
		qw422016.N().S(`  <div class="card">
    <h3>Revisions</h3>
`)
//line views/vversion/Detail.html:58
		prms := p.Params.Get("version", nil, ps.Logger).Sanitize("version")

//line views/vversion/Detail.html:58
		qw422016.N().S(`    <table class="mt">
      <thead>
        <tr>
          `)
//line views/vversion/Detail.html:62
		components.StreamTableHeaderSimple(qw422016, "version", "id", "ID", "String text", prms, ps.URI, ps)
//line views/vversion/Detail.html:62
		qw422016.N().S(`
          `)
//line views/vversion/Detail.html:63
		components.StreamTableHeaderSimple(qw422016, "version", "revision", "Revision", "Integer", prms, ps.URI, ps)
//line views/vversion/Detail.html:63
		qw422016.N().S(`
          `)
//line views/vversion/Detail.html:64
		components.StreamTableHeaderSimple(qw422016, "version", "created", "Created", "Date and time, in almost any format", prms, ps.URI, ps)
//line views/vversion/Detail.html:64
		qw422016.N().S(`
        </tr>
      </thead>
      <tbody>
`)
//line views/vversion/Detail.html:68
		for _, model := range p.Revisions {
//line views/vversion/Detail.html:68
			qw422016.N().S(`        <tr>
          <td><a href="/version/`)
//line views/vversion/Detail.html:70
			qw422016.N().U(model.ID)
//line views/vversion/Detail.html:70
			qw422016.N().S(`/revision/`)
//line views/vversion/Detail.html:70
			qw422016.N().D(model.Revision)
//line views/vversion/Detail.html:70
			qw422016.N().S(`">`)
//line views/vversion/Detail.html:70
			qw422016.E().S(model.ID)
//line views/vversion/Detail.html:70
			qw422016.N().S(`</a></td>
          <td><a href="/version/`)
//line views/vversion/Detail.html:71
			qw422016.N().U(model.ID)
//line views/vversion/Detail.html:71
			qw422016.N().S(`/revision/`)
//line views/vversion/Detail.html:71
			qw422016.N().D(model.Revision)
//line views/vversion/Detail.html:71
			qw422016.N().S(`">`)
//line views/vversion/Detail.html:71
			qw422016.N().D(model.Revision)
//line views/vversion/Detail.html:71
			qw422016.N().S(`</a></td>
          <td>`)
//line views/vversion/Detail.html:72
			components.StreamDisplayTimestamp(qw422016, &model.Created)
//line views/vversion/Detail.html:72
			qw422016.N().S(`</td>
        </tr>
`)
//line views/vversion/Detail.html:74
		}
//line views/vversion/Detail.html:74
		qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vversion/Detail.html:78
	}
//line views/vversion/Detail.html:80
	qw422016.N().S(`  `)
//line views/vversion/Detail.html:81
	components.StreamJSONModal(qw422016, "version", "Version JSON", p.Model, 1)
//line views/vversion/Detail.html:81
	qw422016.N().S(`
`)
//line views/vversion/Detail.html:82
}

//line views/vversion/Detail.html:82
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vversion/Detail.html:82
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vversion/Detail.html:82
	p.StreamBody(qw422016, as, ps)
//line views/vversion/Detail.html:82
	qt422016.ReleaseWriter(qw422016)
//line views/vversion/Detail.html:82
}

//line views/vversion/Detail.html:82
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vversion/Detail.html:82
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vversion/Detail.html:82
	p.WriteBody(qb422016, as, ps)
//line views/vversion/Detail.html:82
	qs422016 := string(qb422016.B)
//line views/vversion/Detail.html:82
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vversion/Detail.html:82
	return qs422016
//line views/vversion/Detail.html:82
}
