// Content managed by Project Forge, see [projectforge.md] for details.
package controller

import (
	"github.com/fasthttp/router"
	"github.com/valyala/fasthttp"

	"github.com/kyleu/pftest/app/lib/telemetry/httpmetrics"
	"github.com/kyleu/pftest/app/util"
)

//nolint
func AppRoutes() fasthttp.RequestHandler {
	r := router.New()

	r.GET("/", Home)
	r.GET("/healthcheck", Healthcheck)
	r.GET("/about", About)
	r.GET("/theme", ThemeList)
	r.GET("/theme/{key}", ThemeEdit)
	r.POST("/theme/{key}", ThemeSave)
	r.GET(defaultSearchPath, Search)

	r.GET(defaultProfilePath, Profile)
	r.POST(defaultProfilePath, ProfileSave)
	r.GET("/auth/{key}", AuthDetail)
	r.GET("/auth/callback/{key}", AuthCallback)
	r.GET("/auth/logout/{key}", AuthLogout)

	// $PF_INJECT_START(codegen)$
	r.GET("/basic", BasicList)
	r.GET("/basic/random", BasicCreateFormRandom)
	r.GET("/basic/new", BasicCreateForm)
	r.POST("/basic/new", BasicCreate)
	r.GET("/basic/{id}", BasicDetail)
	r.GET("/basic/{id}/edit", BasicEditForm)
	r.POST("/basic/{id}/edit", BasicEdit)
	r.GET("/basic/{id}/delete", BasicDelete)
	r.GET("/reference", ReferenceList)
	r.GET("/reference/random", ReferenceCreateFormRandom)
	r.GET("/reference/new", ReferenceCreateForm)
	r.POST("/reference/new", ReferenceCreate)
	r.GET("/reference/{id}", ReferenceDetail)
	r.GET("/reference/{id}/edit", ReferenceEditForm)
	r.POST("/reference/{id}/edit", ReferenceEdit)
	r.GET("/reference/{id}/delete", ReferenceDelete)
	r.GET("/audited", AuditedList)
	r.GET("/audited/random", AuditedCreateFormRandom)
	r.GET("/audited/new", AuditedCreateForm)
	r.POST("/audited/new", AuditedCreate)
	r.GET("/audited/{id}", AuditedDetail)
	r.GET("/audited/{id}/edit", AuditedEditForm)
	r.POST("/audited/{id}/edit", AuditedEdit)
	r.GET("/audited/{id}/delete", AuditedDelete)
	r.GET("/timestamp", TimestampList)
	r.GET("/timestamp/random", TimestampCreateFormRandom)
	r.GET("/timestamp/new", TimestampCreateForm)
	r.POST("/timestamp/new", TimestampCreate)
	r.GET("/timestamp/{id}", TimestampDetail)
	r.GET("/timestamp/{id}/edit", TimestampEditForm)
	r.POST("/timestamp/{id}/edit", TimestampEdit)
	r.GET("/timestamp/{id}/delete", TimestampDelete)
	r.GET("/version", VersionList)
	r.GET("/version/random", VersionCreateFormRandom)
	r.GET("/version/new", VersionCreateForm)
	r.POST("/version/new", VersionCreate)
	r.GET("/version/{id}", VersionDetail)
	r.GET("/version/{id}/edit", VersionEditForm)
	r.POST("/version/{id}/edit", VersionEdit)
	r.GET("/version/{id}/delete", VersionDelete)
	r.GET("/version/{id}/revision/{revision}", VersionRevision)
	r.GET("/history", HistoryList)
	r.GET("/history/random", HistoryCreateFormRandom)
	r.GET("/history/new", HistoryCreateForm)
	r.POST("/history/new", HistoryCreate)
	r.GET("/history/{id}", HistoryDetail)
	r.GET("/history/{id}/edit", HistoryEditForm)
	r.POST("/history/{id}/edit", HistoryEdit)
	r.GET("/history/{id}/delete", HistoryDelete)
	r.GET("/history/{id}/history/{historyID}", HistoryHistory)
	r.GET("/softdel", SoftdelList)
	r.GET("/softdel/random", SoftdelCreateFormRandom)
	r.GET("/softdel/new", SoftdelCreateForm)
	r.POST("/softdel/new", SoftdelCreate)
	r.GET("/softdel/{id}", SoftdelDetail)
	r.GET("/softdel/{id}/edit", SoftdelEditForm)
	r.POST("/softdel/{id}/edit", SoftdelEdit)
	r.GET("/softdel/{id}/delete", SoftdelDelete)
	r.GET("/group/group", GroupGroupList)
	r.GET("/group/group/{group}", GroupListByGroup)
	r.GET("/group/group/{group}/new", GroupCreateFormByGroup)
	r.POST("/group/group/{group}/new", GroupCreateByGroup)
	r.GET("/group/group/{group}/{id}", GroupDetailByGroup)
	r.GET("/group/group/{group}/{id}/edit", GroupEditFormByGroup)
	r.POST("/group/group/{group}/{id}/edit", GroupEditByGroup)
	r.GET("/group", GroupList)
	r.GET("/group/random", GroupCreateFormRandom)
	r.GET("/group/new", GroupCreateForm)
	r.POST("/group/new", GroupCreate)
	r.GET("/group/{id}", GroupDetail)
	r.GET("/group/{id}/edit", GroupEditForm)
	r.POST("/group/{id}/edit", GroupEdit)
	r.GET("/group/{id}/delete", GroupDelete)
	r.GET("/capital", CapitalList)
	r.GET("/capital/random", CapitalCreateFormRandom)
	r.GET("/capital/new", CapitalCreateForm)
	r.POST("/capital/new", CapitalCreate)
	r.GET("/capital/{id}", CapitalDetail)
	r.GET("/capital/{id}/edit", CapitalEditForm)
	r.POST("/capital/{id}/edit", CapitalEdit)
	r.GET("/capital/{id}/delete", CapitalDelete)
	r.GET("/capital/{id}/Version/{Version}", CapitalVersion)
	r.GET("/mixedcase", MixedCaseList)
	r.GET("/mixedcase/random", MixedCaseCreateFormRandom)
	r.GET("/mixedcase/new", MixedCaseCreateForm)
	r.POST("/mixedcase/new", MixedCaseCreate)
	r.GET("/mixedcase/{id}", MixedCaseDetail)
	r.GET("/mixedcase/{id}/edit", MixedCaseEditForm)
	r.POST("/mixedcase/{id}/edit", MixedCaseEdit)
	r.GET("/mixedcase/{id}/delete", MixedCaseDelete)
	r.GET("/troub/le", TroubleList)
	r.GET("/troub/le/random", TroubleCreateFormRandom)
	r.GET("/troub/le/new", TroubleCreateForm)
	r.POST("/troub/le/new", TroubleCreate)
	r.GET("/troub/le/{from}/{where}", TroubleDetail)
	r.GET("/troub/le/{from}/{where}/edit", TroubleEditForm)
	r.POST("/troub/le/{from}/{where}/edit", TroubleEdit)
	r.GET("/troub/le/{from}/{where}/delete", TroubleDelete)
	r.GET("/troub/le/{from}/{where}/selectcol/{selectcol}", TroubleSelectcol)
	// $PF_INJECT_END(codegen)$

	// $PF_SECTION_START(routes)$
	// $PF_SECTION_END(routes)$

	r.GET("/admin", Admin)
	r.GET("/admin/sandbox", SandboxList)
	r.GET("/admin/sandbox/{key}", SandboxRun)
	r.GET("/admin/audit", AuditList)
	r.GET("/admin/audit/random", AuditCreateFormRandom)
	r.GET("/admin/audit/new", AuditCreateForm)
	r.POST("/admin/audit/new", AuditCreate)
	r.GET("/admin/audit/record/{id}", RecordDetail)
	r.GET("/admin/audit/{id}", AuditDetail)
	r.GET("/admin/audit/{id}/edit", AuditEditForm)
	r.POST("/admin/audit/{id}/edit", AuditEdit)
	r.GET("/admin/audit/{id}/delete", AuditDelete)
	r.GET("/admin/database", DatabaseList)
	r.GET("/admin/database/{key}", DatabaseDetail)
	r.GET("/admin/database/{key}/{act}", DatabaseAction)
	r.POST("/admin/database/{key}/sql", DatabaseSQLRun)
	r.GET("/admin/{path:*}", Admin)

	r.GET("/favicon.ico", Favicon)
	r.GET("/robots.txt", RobotsTxt)
	r.GET("/assets/{_:*}", Static)

	r.OPTIONS("/", Options)
	r.OPTIONS("/{_:*}", Options)
	r.NotFound = NotFound

	p := httpmetrics.NewMetrics(util.AppKey)
	return fasthttp.CompressHandlerLevel(p.WrapHandler(r), fasthttp.CompressBestSpeed)
}
