// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vbasic/Detail.html:2
package vbasic

//line views/vbasic/Detail.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/basic"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/app/relation"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
	"github.com/kyleu/pftest/views/vrelation"
)

//line views/vbasic/Detail.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vbasic/Detail.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vbasic/Detail.html:13
type Detail struct {
	layout.Basic
	Model              *basic.Basic
	Params             filter.ParamSet
	RelationsByBasicID relation.Relations
}

//line views/vbasic/Detail.html:20
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vbasic/Detail.html:20
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-basic"><button type="button">JSON</button></a>
      <a href="`)
//line views/vbasic/Detail.html:24
	qw422016.E().S(p.Model.WebPath())
//line views/vbasic/Detail.html:24
	qw422016.N().S(`/edit"><button>Edit</button></a>
    </div>
    <h3>`)
//line views/vbasic/Detail.html:26
	components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vbasic/Detail.html:26
	qw422016.N().S(` `)
//line views/vbasic/Detail.html:26
	qw422016.E().S(p.Model.TitleString())
//line views/vbasic/Detail.html:26
	qw422016.N().S(`</h3>
    <div><a href="/basic"><em>Basic</em></a></div>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
          <td>`)
//line views/vbasic/Detail.html:32
	components.StreamDisplayUUID(qw422016, &p.Model.ID)
//line views/vbasic/Detail.html:32
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Name</th>
          <td><strong>`)
//line views/vbasic/Detail.html:36
	qw422016.E().S(p.Model.Name)
//line views/vbasic/Detail.html:36
	qw422016.N().S(`</strong></td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Status</th>
          <td><strong>`)
//line views/vbasic/Detail.html:40
	qw422016.E().S(p.Model.Status)
//line views/vbasic/Detail.html:40
	qw422016.N().S(`</strong></td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Created</th>
          <td>`)
//line views/vbasic/Detail.html:44
	components.StreamDisplayTimestamp(qw422016, &p.Model.Created)
//line views/vbasic/Detail.html:44
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vbasic/Detail.html:51
	if len(p.RelationsByBasicID) > 0 {
//line views/vbasic/Detail.html:51
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vbasic/Detail.html:53
		components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vbasic/Detail.html:53
		qw422016.N().S(` Related relations by [basic id]</h3>
    `)
//line views/vbasic/Detail.html:54
		vrelation.StreamTable(qw422016, p.RelationsByBasicID, nil, p.Params, as, ps)
//line views/vbasic/Detail.html:54
		qw422016.N().S(`
  </div>
`)
//line views/vbasic/Detail.html:56
	}
//line views/vbasic/Detail.html:56
	qw422016.N().S(`  `)
//line views/vbasic/Detail.html:57
	components.StreamJSONModal(qw422016, "basic", "Basic JSON", p.Model, 1)
//line views/vbasic/Detail.html:57
	qw422016.N().S(`
`)
//line views/vbasic/Detail.html:58
}

//line views/vbasic/Detail.html:58
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vbasic/Detail.html:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vbasic/Detail.html:58
	p.StreamBody(qw422016, as, ps)
//line views/vbasic/Detail.html:58
	qt422016.ReleaseWriter(qw422016)
//line views/vbasic/Detail.html:58
}

//line views/vbasic/Detail.html:58
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vbasic/Detail.html:58
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vbasic/Detail.html:58
	p.WriteBody(qb422016, as, ps)
//line views/vbasic/Detail.html:58
	qs422016 := string(qb422016.B)
//line views/vbasic/Detail.html:58
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vbasic/Detail.html:58
	return qs422016
//line views/vbasic/Detail.html:58
}
