// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vmixedcase/Detail.html:1
package vmixedcase

//line views/vmixedcase/Detail.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/mixedcase"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/view"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vmixedcase/Detail.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vmixedcase/Detail.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vmixedcase/Detail.html:10
type Detail struct {
	layout.Basic
	Model *mixedcase.MixedCase
}

//line views/vmixedcase/Detail.html:15
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmixedcase/Detail.html:15
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-mixedCase"><button type="button">`)
//line views/vmixedcase/Detail.html:18
	components.StreamSVGButton(qw422016, "file", ps)
//line views/vmixedcase/Detail.html:18
	qw422016.N().S(` JSON</button></a>
      <a href="`)
//line views/vmixedcase/Detail.html:19
	qw422016.E().S(p.Model.WebPath())
//line views/vmixedcase/Detail.html:19
	qw422016.N().S(`/edit"><button>`)
//line views/vmixedcase/Detail.html:19
	components.StreamSVGButton(qw422016, "edit", ps)
//line views/vmixedcase/Detail.html:19
	qw422016.N().S(` Edit</button></a>
    </div>
    <h3>`)
//line views/vmixedcase/Detail.html:21
	components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vmixedcase/Detail.html:21
	qw422016.N().S(` `)
//line views/vmixedcase/Detail.html:21
	qw422016.E().S(p.Model.TitleString())
//line views/vmixedcase/Detail.html:21
	qw422016.N().S(`</h3>
    <div><a href="/mixedcase"><em>Mixed Case</em></a></div>
    <div class="mt overflow full-width">
      <table>
        <tbody>
          <tr>
            <th class="shrink" title="String text">ID</th>
            <td>`)
//line views/vmixedcase/Detail.html:28
	view.StreamString(qw422016, p.Model.ID)
//line views/vmixedcase/Detail.html:28
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Test Field</th>
            <td>`)
//line views/vmixedcase/Detail.html:32
	view.StreamString(qw422016, p.Model.TestField)
//line views/vmixedcase/Detail.html:32
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Another Field</th>
            <td>`)
//line views/vmixedcase/Detail.html:36
	view.StreamString(qw422016, p.Model.AnotherField)
//line views/vmixedcase/Detail.html:36
	qw422016.N().S(`</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
`)
//line views/vmixedcase/Detail.html:43
	qw422016.N().S(`  `)
//line views/vmixedcase/Detail.html:44
	components.StreamJSONModal(qw422016, "mixedCase", "Mixed Case JSON", p.Model, 1)
//line views/vmixedcase/Detail.html:44
	qw422016.N().S(`
`)
//line views/vmixedcase/Detail.html:45
}

//line views/vmixedcase/Detail.html:45
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmixedcase/Detail.html:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vmixedcase/Detail.html:45
	p.StreamBody(qw422016, as, ps)
//line views/vmixedcase/Detail.html:45
	qt422016.ReleaseWriter(qw422016)
//line views/vmixedcase/Detail.html:45
}

//line views/vmixedcase/Detail.html:45
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vmixedcase/Detail.html:45
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vmixedcase/Detail.html:45
	p.WriteBody(qb422016, as, ps)
//line views/vmixedcase/Detail.html:45
	qs422016 := string(qb422016.B)
//line views/vmixedcase/Detail.html:45
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vmixedcase/Detail.html:45
	return qs422016
//line views/vmixedcase/Detail.html:45
}
