// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vmixedcase/Detail.html:2
package vmixedcase

//line views/vmixedcase/Detail.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/mixedcase"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vmixedcase/Detail.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vmixedcase/Detail.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vmixedcase/Detail.html:10
type Detail struct {
	layout.Basic
	Model *mixedcase.MixedCase
}

//line views/vmixedcase/Detail.html:15
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmixedcase/Detail.html:15
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-mixedCase"><button type="button">JSON</button></a>
      <a href="`)
//line views/vmixedcase/Detail.html:19
	qw422016.E().S(p.Model.WebPath())
//line views/vmixedcase/Detail.html:19
	qw422016.N().S(`/edit"><button>Edit</button></a>
    </div>
    <h3>`)
//line views/vmixedcase/Detail.html:21
	components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vmixedcase/Detail.html:21
	qw422016.N().S(` `)
//line views/vmixedcase/Detail.html:21
	qw422016.E().S(p.Model.TitleString())
//line views/vmixedcase/Detail.html:21
	qw422016.N().S(`</h3>
    <div><a href="/mixedcase"><em>Mixed Case</em></a></div>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="String text">ID</th>
          <td>`)
//line views/vmixedcase/Detail.html:27
	qw422016.E().S(p.Model.ID)
//line views/vmixedcase/Detail.html:27
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Test Field</th>
          <td>`)
//line views/vmixedcase/Detail.html:31
	qw422016.E().S(p.Model.TestField)
//line views/vmixedcase/Detail.html:31
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Another Field</th>
          <td>`)
//line views/vmixedcase/Detail.html:35
	qw422016.E().S(p.Model.AnotherField)
//line views/vmixedcase/Detail.html:35
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vmixedcase/Detail.html:41
	qw422016.N().S(`  `)
//line views/vmixedcase/Detail.html:42
	components.StreamJSONModal(qw422016, "mixedCase", "Mixed Case JSON", p.Model, 1)
//line views/vmixedcase/Detail.html:42
	qw422016.N().S(`
`)
//line views/vmixedcase/Detail.html:43
}

//line views/vmixedcase/Detail.html:43
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmixedcase/Detail.html:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vmixedcase/Detail.html:43
	p.StreamBody(qw422016, as, ps)
//line views/vmixedcase/Detail.html:43
	qt422016.ReleaseWriter(qw422016)
//line views/vmixedcase/Detail.html:43
}

//line views/vmixedcase/Detail.html:43
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vmixedcase/Detail.html:43
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vmixedcase/Detail.html:43
	p.WriteBody(qb422016, as, ps)
//line views/vmixedcase/Detail.html:43
	qs422016 := string(qb422016.B)
//line views/vmixedcase/Detail.html:43
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vmixedcase/Detail.html:43
	return qs422016
//line views/vmixedcase/Detail.html:43
}
