// Code generated by qtc from "Edit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vmixedcase/Edit.html:2
package vmixedcase

//line views/vmixedcase/Edit.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/mixedcase"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vmixedcase/Edit.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vmixedcase/Edit.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vmixedcase/Edit.html:10
type Edit struct {
	layout.Basic
	Model *mixedcase.MixedCase
	IsNew bool
}

//line views/vmixedcase/Edit.html:16
func (p *Edit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmixedcase/Edit.html:16
	qw422016.N().S(`
  <div class="card">
`)
//line views/vmixedcase/Edit.html:18
	if p.IsNew {
//line views/vmixedcase/Edit.html:18
		qw422016.N().S(`    <div class="right"><a href="/mixedcase/random"><button>Random</button></a></div>
    <h3>`)
//line views/vmixedcase/Edit.html:20
		components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vmixedcase/Edit.html:20
		qw422016.N().S(` New Mixed Case</h3>
    <form action="/mixedcase/new" class="mt" method="post">
`)
//line views/vmixedcase/Edit.html:22
	} else {
//line views/vmixedcase/Edit.html:22
		qw422016.N().S(`    <div class="right"><a href="`)
//line views/vmixedcase/Edit.html:23
		qw422016.E().S(p.Model.WebPath())
//line views/vmixedcase/Edit.html:23
		qw422016.N().S(`/delete" onclick="return confirm('Are you sure you wish to delete mixed case [`)
//line views/vmixedcase/Edit.html:23
		qw422016.E().S(p.Model.String())
//line views/vmixedcase/Edit.html:23
		qw422016.N().S(`]?')"><button>Delete</button></a></div>
    <h3>`)
//line views/vmixedcase/Edit.html:24
		components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vmixedcase/Edit.html:24
		qw422016.N().S(` Edit Mixed Case [`)
//line views/vmixedcase/Edit.html:24
		qw422016.E().S(p.Model.String())
//line views/vmixedcase/Edit.html:24
		qw422016.N().S(`]</h3>
    <form action="" method="post">
`)
//line views/vmixedcase/Edit.html:26
	}
//line views/vmixedcase/Edit.html:26
	qw422016.N().S(`      <table class="mt expanded">
        <tbody>
          `)
//line views/vmixedcase/Edit.html:29
	if p.IsNew {
//line views/vmixedcase/Edit.html:29
		components.StreamTableInput(qw422016, "id", "", "ID", p.Model.ID, 5, "String text")
//line views/vmixedcase/Edit.html:29
	}
//line views/vmixedcase/Edit.html:29
	qw422016.N().S(`
          `)
//line views/vmixedcase/Edit.html:30
	components.StreamTableInput(qw422016, "testField", "", "Test Field", p.Model.TestField, 5, "String text")
//line views/vmixedcase/Edit.html:30
	qw422016.N().S(`
          `)
//line views/vmixedcase/Edit.html:31
	components.StreamTableInput(qw422016, "anotherField", "", "Another Field", p.Model.AnotherField, 5, "String text")
//line views/vmixedcase/Edit.html:31
	qw422016.N().S(`
          <tr><td colspan="2"><button type="submit">Save Changes</button></td></tr>
        </tbody>
      </table>
    </form>
  </div>
`)
//line views/vmixedcase/Edit.html:37
}

//line views/vmixedcase/Edit.html:37
func (p *Edit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vmixedcase/Edit.html:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vmixedcase/Edit.html:37
	p.StreamBody(qw422016, as, ps)
//line views/vmixedcase/Edit.html:37
	qt422016.ReleaseWriter(qw422016)
//line views/vmixedcase/Edit.html:37
}

//line views/vmixedcase/Edit.html:37
func (p *Edit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vmixedcase/Edit.html:37
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vmixedcase/Edit.html:37
	p.WriteBody(qb422016, as, ps)
//line views/vmixedcase/Edit.html:37
	qs422016 := string(qb422016.B)
//line views/vmixedcase/Edit.html:37
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vmixedcase/Edit.html:37
	return qs422016
//line views/vmixedcase/Edit.html:37
}
