// Code generated by qtc from "Any.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/view/Any.html:1
package view

//line views/components/view/Any.html:1
import (
	"fmt"
	"net/url"
	"time"

	"github.com/google/uuid"

	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/util"
	"github.com/kyleu/pftest/app/util/numeric"
)

//line views/components/view/Any.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/view/Any.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/view/Any.html:13
func StreamAny(qw422016 *qt422016.Writer, x any, ps *cutil.PageState) {
//line views/components/view/Any.html:14
	if x == nil {
//line views/components/view/Any.html:14
		qw422016.N().S(`<em>nil</em>`)
//line views/components/view/Any.html:16
	} else {
//line views/components/view/Any.html:17
		switch t := x.(type) {
//line views/components/view/Any.html:18
		case bool:
//line views/components/view/Any.html:19
			StreamBool(qw422016, t)
//line views/components/view/Any.html:20
		case util.Diffs:
//line views/components/view/Any.html:21
			StreamDiffs(qw422016, t)
//line views/components/view/Any.html:22
		case float32:
//line views/components/view/Any.html:23
			StreamFloat(qw422016, t)
//line views/components/view/Any.html:24
		case float64:
//line views/components/view/Any.html:25
			StreamFloat(qw422016, t)
//line views/components/view/Any.html:26
		case int:
//line views/components/view/Any.html:27
			StreamInt(qw422016, t)
//line views/components/view/Any.html:28
		case int32:
//line views/components/view/Any.html:29
			StreamInt(qw422016, t)
//line views/components/view/Any.html:30
		case int64:
//line views/components/view/Any.html:31
			StreamInt(qw422016, t)
//line views/components/view/Any.html:32
		case util.ToOrderedMap[any]:
//line views/components/view/Any.html:33
			StreamOrderedMap(qw422016, false, t.ToOrderedMap(), ps)
//line views/components/view/Any.html:34
		case *util.OrderedMap[any]:
//line views/components/view/Any.html:35
			StreamOrderedMap(qw422016, false, t, ps)
//line views/components/view/Any.html:36
		case util.ToOrderedMaps[any]:
//line views/components/view/Any.html:37
			StreamOrderedMapArray(qw422016, false, ps, t.ToOrderedMaps()...)
//line views/components/view/Any.html:38
		case []*util.OrderedMap[any]:
//line views/components/view/Any.html:39
			StreamOrderedMapArray(qw422016, false, ps, t...)
//line views/components/view/Any.html:40
		case util.ToMap:
//line views/components/view/Any.html:41
			StreamMap(qw422016, false, t.ToMap(), ps)
//line views/components/view/Any.html:42
		case util.ValueMap:
//line views/components/view/Any.html:43
			StreamMap(qw422016, false, t, ps)
//line views/components/view/Any.html:44
		case map[string]any:
//line views/components/view/Any.html:45
			StreamMap(qw422016, false, t, ps)
//line views/components/view/Any.html:46
		case util.ToMaps:
//line views/components/view/Any.html:47
			StreamMapArray(qw422016, false, ps, t.ToMaps()...)
//line views/components/view/Any.html:48
		case []util.ValueMap:
//line views/components/view/Any.html:49
			StreamMapArray(qw422016, false, ps, t...)
//line views/components/view/Any.html:50
		case numeric.Numeric:
//line views/components/view/Any.html:51
			StreamNumeric(qw422016, t)
//line views/components/view/Any.html:52
		case util.Pkg:
//line views/components/view/Any.html:53
			StreamPackage(qw422016, t)
//line views/components/view/Any.html:54
		case string:
//line views/components/view/Any.html:55
			StreamString(qw422016, t)
//line views/components/view/Any.html:56
		case []string:
//line views/components/view/Any.html:57
			StreamStringArray(qw422016, t)
//line views/components/view/Any.html:58
		case time.Time:
//line views/components/view/Any.html:59
			StreamTimestamp(qw422016, &t)
//line views/components/view/Any.html:60
		case *time.Time:
//line views/components/view/Any.html:61
			StreamTimestamp(qw422016, t)
//line views/components/view/Any.html:62
		case url.URL:
//line views/components/view/Any.html:63
			StreamURL(qw422016, t, "", true, ps)
//line views/components/view/Any.html:64
		case *url.URL:
//line views/components/view/Any.html:65
			StreamURL(qw422016, t, "", true, ps)
//line views/components/view/Any.html:66
		case uuid.UUID:
//line views/components/view/Any.html:67
			StreamUUID(qw422016, &t)
//line views/components/view/Any.html:68
		case *uuid.UUID:
//line views/components/view/Any.html:69
			StreamUUID(qw422016, t)
//line views/components/view/Any.html:70
		case []any:
//line views/components/view/Any.html:71
			if len(t) == 0 {
//line views/components/view/Any.html:71
				qw422016.N().S(`<em>empty array</em>`)
//line views/components/view/Any.html:73
			} else {
//line views/components/view/Any.html:74
				arr, extra := util.ArrayLimit(t, 8)

//line views/components/view/Any.html:75
				for idx, e := range arr {
//line views/components/view/Any.html:75
					qw422016.N().S(`<div class="flex bb"><div class="mts mrs mbs"><em>`)
//line views/components/view/Any.html:77
					qw422016.N().D(idx + 1)
//line views/components/view/Any.html:77
					qw422016.N().S(`</em></div><div class="mts mbs">`)
//line views/components/view/Any.html:78
					StreamAny(qw422016, e, ps)
//line views/components/view/Any.html:78
					qw422016.N().S(`</div></div>`)
//line views/components/view/Any.html:80
				}
//line views/components/view/Any.html:81
				if extra > 0 {
//line views/components/view/Any.html:81
					qw422016.N().S(`<div class="mts"><em>...and`)
//line views/components/view/Any.html:82
					qw422016.N().S(` `)
//line views/components/view/Any.html:82
					qw422016.N().D(extra)
//line views/components/view/Any.html:82
					qw422016.N().S(` `)
//line views/components/view/Any.html:82
					qw422016.N().S(`more</em></div>`)
//line views/components/view/Any.html:83
				}
//line views/components/view/Any.html:84
			}
//line views/components/view/Any.html:85
		case fmt.Stringer:
//line views/components/view/Any.html:86
			StreamString(qw422016, t.String())
//line views/components/view/Any.html:87
		default:
//line views/components/view/Any.html:87
			qw422016.N().S(`unhandled type [`)
//line views/components/view/Any.html:88
			qw422016.E().S(fmt.Sprintf("%T", x))
//line views/components/view/Any.html:88
			qw422016.N().S(`]`)
//line views/components/view/Any.html:89
		}
//line views/components/view/Any.html:90
	}
//line views/components/view/Any.html:91
}

//line views/components/view/Any.html:91
func WriteAny(qq422016 qtio422016.Writer, x any, ps *cutil.PageState) {
//line views/components/view/Any.html:91
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/view/Any.html:91
	StreamAny(qw422016, x, ps)
//line views/components/view/Any.html:91
	qt422016.ReleaseWriter(qw422016)
//line views/components/view/Any.html:91
}

//line views/components/view/Any.html:91
func Any(x any, ps *cutil.PageState) string {
//line views/components/view/Any.html:91
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/view/Any.html:91
	WriteAny(qb422016, x, ps)
//line views/components/view/Any.html:91
	qs422016 := string(qb422016.B)
//line views/components/view/Any.html:91
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/view/Any.html:91
	return qs422016
//line views/components/view/Any.html:91
}
