// Code generated by qtc from "Any.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/view/Any.html:1
package view

//line views/components/view/Any.html:1
import (
	"fmt"
	"net/url"
	"time"

	"github.com/google/uuid"

	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/util"
	"github.com/kyleu/pftest/app/util/numeric"
	"github.com/kyleu/pftest/views/components"
)

//line views/components/view/Any.html:14
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/view/Any.html:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/view/Any.html:14
func StreamAny(qw422016 *qt422016.Writer, x any, ps *cutil.PageState) {
//line views/components/view/Any.html:15
	if x == nil {
//line views/components/view/Any.html:15
		qw422016.N().S(`<em>nil</em>`)
//line views/components/view/Any.html:17
	} else {
//line views/components/view/Any.html:18
		switch t := x.(type) {
//line views/components/view/Any.html:19
		case bool:
//line views/components/view/Any.html:20
			StreamBool(qw422016, t)
//line views/components/view/Any.html:21
		case util.Diffs:
//line views/components/view/Any.html:22
			StreamDiffs(qw422016, t)
//line views/components/view/Any.html:23
		case float32:
//line views/components/view/Any.html:24
			StreamFloat(qw422016, t)
//line views/components/view/Any.html:25
		case float64:
//line views/components/view/Any.html:26
			StreamFloat(qw422016, t)
//line views/components/view/Any.html:27
		case int:
//line views/components/view/Any.html:28
			StreamInt(qw422016, t)
//line views/components/view/Any.html:29
		case int32:
//line views/components/view/Any.html:30
			StreamInt(qw422016, t)
//line views/components/view/Any.html:31
		case int64:
//line views/components/view/Any.html:32
			StreamInt(qw422016, t)
//line views/components/view/Any.html:33
		case util.ToOrderedMap[any]:
//line views/components/view/Any.html:34
			StreamOrderedMap(qw422016, false, t.ToOrderedMap(), ps)
//line views/components/view/Any.html:35
		case *util.OrderedMap[any]:
//line views/components/view/Any.html:36
			StreamOrderedMap(qw422016, false, t, ps)
//line views/components/view/Any.html:37
		case util.ToOrderedMaps[any]:
//line views/components/view/Any.html:38
			StreamOrderedMapArray(qw422016, false, ps, t.ToOrderedMaps()...)
//line views/components/view/Any.html:39
		case []*util.OrderedMap[any]:
//line views/components/view/Any.html:40
			StreamOrderedMapArray(qw422016, false, ps, t...)
//line views/components/view/Any.html:41
		case util.ToMap:
//line views/components/view/Any.html:42
			StreamMap(qw422016, false, t.ToMap(), ps)
//line views/components/view/Any.html:43
		case util.ValueMap:
//line views/components/view/Any.html:44
			StreamMap(qw422016, false, t, ps)
//line views/components/view/Any.html:45
		case map[string]any:
//line views/components/view/Any.html:46
			StreamMap(qw422016, false, t, ps)
//line views/components/view/Any.html:47
		case util.ToMaps:
//line views/components/view/Any.html:48
			StreamMapArray(qw422016, false, ps, t.ToMaps()...)
//line views/components/view/Any.html:49
		case []util.ValueMap:
//line views/components/view/Any.html:50
			StreamMapArray(qw422016, false, ps, t...)
//line views/components/view/Any.html:51
		case numeric.Numeric:
//line views/components/view/Any.html:52
			StreamNumeric(qw422016, t)
//line views/components/view/Any.html:53
		case util.Pkg:
//line views/components/view/Any.html:54
			StreamPackage(qw422016, t)
//line views/components/view/Any.html:55
		case string:
//line views/components/view/Any.html:56
			StreamString(qw422016, t)
//line views/components/view/Any.html:57
		case []string:
//line views/components/view/Any.html:58
			StreamStringArray(qw422016, t)
//line views/components/view/Any.html:59
		case time.Time:
//line views/components/view/Any.html:60
			StreamTimestamp(qw422016, &t)
//line views/components/view/Any.html:61
		case *time.Time:
//line views/components/view/Any.html:62
			StreamTimestamp(qw422016, t)
//line views/components/view/Any.html:63
		case url.URL:
//line views/components/view/Any.html:64
			StreamURL(qw422016, t, "", true, ps)
//line views/components/view/Any.html:65
		case *url.URL:
//line views/components/view/Any.html:66
			StreamURL(qw422016, t, "", true, ps)
//line views/components/view/Any.html:67
		case uuid.UUID:
//line views/components/view/Any.html:68
			StreamUUID(qw422016, &t)
//line views/components/view/Any.html:69
		case *uuid.UUID:
//line views/components/view/Any.html:70
			StreamUUID(qw422016, t)
//line views/components/view/Any.html:71
		case []any:
//line views/components/view/Any.html:72
			if len(t) == 0 {
//line views/components/view/Any.html:72
				qw422016.N().S(`<em>empty array</em>`)
//line views/components/view/Any.html:74
			} else {
//line views/components/view/Any.html:75
				arr, extra := util.ArrayLimit(t, 8)

//line views/components/view/Any.html:76
				for idx, e := range arr {
//line views/components/view/Any.html:76
					qw422016.N().S(`<div class="flex bb"><div class="mts mrs mbs"><em>`)
//line views/components/view/Any.html:78
					qw422016.N().D(idx + 1)
//line views/components/view/Any.html:78
					qw422016.N().S(`</em></div><div class="mts mbs">`)
//line views/components/view/Any.html:79
					StreamAny(qw422016, e, ps)
//line views/components/view/Any.html:79
					qw422016.N().S(`</div></div>`)
//line views/components/view/Any.html:81
				}
//line views/components/view/Any.html:82
				if extra > 0 {
//line views/components/view/Any.html:82
					qw422016.N().S(`<div class="mts"><em>...and`)
//line views/components/view/Any.html:83
					qw422016.N().S(` `)
//line views/components/view/Any.html:83
					qw422016.N().D(extra)
//line views/components/view/Any.html:83
					qw422016.N().S(` `)
//line views/components/view/Any.html:83
					qw422016.N().S(`more</em></div>`)
//line views/components/view/Any.html:84
				}
//line views/components/view/Any.html:85
			}
//line views/components/view/Any.html:86
		case fmt.Stringer:
//line views/components/view/Any.html:87
			StreamString(qw422016, t.String())
//line views/components/view/Any.html:88
		default:
//line views/components/view/Any.html:88
			qw422016.N().S(`unhandled type [`)
//line views/components/view/Any.html:89
			qw422016.E().S(fmt.Sprintf("%T", x))
//line views/components/view/Any.html:89
			qw422016.N().S(`]`)
//line views/components/view/Any.html:90
		}
//line views/components/view/Any.html:91
	}
//line views/components/view/Any.html:92
}

//line views/components/view/Any.html:92
func WriteAny(qq422016 qtio422016.Writer, x any, ps *cutil.PageState) {
//line views/components/view/Any.html:92
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/view/Any.html:92
	StreamAny(qw422016, x, ps)
//line views/components/view/Any.html:92
	qt422016.ReleaseWriter(qw422016)
//line views/components/view/Any.html:92
}

//line views/components/view/Any.html:92
func Any(x any, ps *cutil.PageState) string {
//line views/components/view/Any.html:92
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/view/Any.html:92
	WriteAny(qb422016, x, ps)
//line views/components/view/Any.html:92
	qs422016 := string(qb422016.B)
//line views/components/view/Any.html:92
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/view/Any.html:92
	return qs422016
//line views/components/view/Any.html:92
}

//line views/components/view/Any.html:94
func StreamAnyTable(qw422016 *qt422016.Writer, title string, value any, indent int, ps *cutil.PageState) {
//line views/components/view/Any.html:94
	qw422016.N().S(`<tr>`)
//line views/components/view/Any.html:96
	components.StreamIndent(qw422016, true, indent+1)
//line views/components/view/Any.html:96
	qw422016.N().S(`<th class="shrink">`)
//line views/components/view/Any.html:97
	qw422016.E().S(title)
//line views/components/view/Any.html:97
	qw422016.N().S(`</th>`)
//line views/components/view/Any.html:98
	components.StreamIndent(qw422016, true, indent+1)
//line views/components/view/Any.html:98
	qw422016.N().S(`<td>`)
//line views/components/view/Any.html:99
	StreamAny(qw422016, value, ps)
//line views/components/view/Any.html:99
	qw422016.N().S(`</td>`)
//line views/components/view/Any.html:100
	components.StreamIndent(qw422016, true, indent)
//line views/components/view/Any.html:100
	qw422016.N().S(`</tr>`)
//line views/components/view/Any.html:102
}

//line views/components/view/Any.html:102
func WriteAnyTable(qq422016 qtio422016.Writer, title string, value any, indent int, ps *cutil.PageState) {
//line views/components/view/Any.html:102
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/view/Any.html:102
	StreamAnyTable(qw422016, title, value, indent, ps)
//line views/components/view/Any.html:102
	qt422016.ReleaseWriter(qw422016)
//line views/components/view/Any.html:102
}

//line views/components/view/Any.html:102
func AnyTable(title string, value any, indent int, ps *cutil.PageState) string {
//line views/components/view/Any.html:102
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/view/Any.html:102
	WriteAnyTable(qb422016, title, value, indent, ps)
//line views/components/view/Any.html:102
	qs422016 := string(qb422016.B)
//line views/components/view/Any.html:102
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/view/Any.html:102
	return qs422016
//line views/components/view/Any.html:102
}
