// Code generated by qtc from "Numeric.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/components/view/Numeric.html:1
package view

//line views/components/view/Numeric.html:1
import (
	"fmt"

	"github.com/kyleu/pftest/app/util"
)

//line views/components/view/Numeric.html:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/components/view/Numeric.html:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/components/view/Numeric.html:7
func StreamNumeric(qw422016 *qt422016.Writer, f any) {
//line views/components/view/Numeric.html:8
	qw422016.E().S(f.(fmt.Stringer).String())
//line views/components/view/Numeric.html:9
}

//line views/components/view/Numeric.html:9
func WriteNumeric(qq422016 qtio422016.Writer, f any) {
//line views/components/view/Numeric.html:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/view/Numeric.html:9
	StreamNumeric(qw422016, f)
//line views/components/view/Numeric.html:9
	qt422016.ReleaseWriter(qw422016)
//line views/components/view/Numeric.html:9
}

//line views/components/view/Numeric.html:9
func Numeric(f any) string {
//line views/components/view/Numeric.html:9
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/view/Numeric.html:9
	WriteNumeric(qb422016, f)
//line views/components/view/Numeric.html:9
	qs422016 := string(qb422016.B)
//line views/components/view/Numeric.html:9
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/view/Numeric.html:9
	return qs422016
//line views/components/view/Numeric.html:9
}

//line views/components/view/Numeric.html:11
func StreamNumericArray(qw422016 *qt422016.Writer, value []any) {
//line views/components/view/Numeric.html:12
	StreamStringArray(qw422016, util.ArrayToStringArray(value))
//line views/components/view/Numeric.html:13
}

//line views/components/view/Numeric.html:13
func WriteNumericArray(qq422016 qtio422016.Writer, value []any) {
//line views/components/view/Numeric.html:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/components/view/Numeric.html:13
	StreamNumericArray(qw422016, value)
//line views/components/view/Numeric.html:13
	qt422016.ReleaseWriter(qw422016)
//line views/components/view/Numeric.html:13
}

//line views/components/view/Numeric.html:13
func NumericArray(value []any) string {
//line views/components/view/Numeric.html:13
	qb422016 := qt422016.AcquireByteBuffer()
//line views/components/view/Numeric.html:13
	WriteNumericArray(qb422016, value)
//line views/components/view/Numeric.html:13
	qs422016 := string(qb422016.B)
//line views/components/view/Numeric.html:13
	qt422016.ReleaseByteBuffer(qb422016)
//line views/components/view/Numeric.html:13
	return qs422016
//line views/components/view/Numeric.html:13
}
