// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vreference/Detail.html:1
package vreference

//line views/vreference/Detail.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/reference"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/view"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vreference/Detail.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vreference/Detail.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vreference/Detail.html:10
type Detail struct {
	layout.Basic
	Model *reference.Reference
	Paths []string
}

//line views/vreference/Detail.html:16
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vreference/Detail.html:16
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-reference"><button type="button" title="JSON">`)
//line views/vreference/Detail.html:19
	components.StreamSVGButton(qw422016, "code", ps)
//line views/vreference/Detail.html:19
	qw422016.N().S(`</button></a>
      <a href="`)
//line views/vreference/Detail.html:20
	qw422016.E().S(p.Model.WebPath(p.Paths...))
//line views/vreference/Detail.html:20
	qw422016.N().S(`/edit" title="Edit"><button>`)
//line views/vreference/Detail.html:20
	components.StreamSVGButton(qw422016, "edit", ps)
//line views/vreference/Detail.html:20
	qw422016.N().S(`</button></a>
    </div>
    <h3>`)
//line views/vreference/Detail.html:22
	components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vreference/Detail.html:22
	qw422016.N().S(` `)
//line views/vreference/Detail.html:22
	qw422016.E().S(p.Model.TitleString())
//line views/vreference/Detail.html:22
	qw422016.N().S(`</h3>
    <div><a href="`)
//line views/vreference/Detail.html:23
	qw422016.E().S(reference.Route(p.Paths...))
//line views/vreference/Detail.html:23
	qw422016.N().S(`"><em>Reference</em></a></div>
    `)
//line views/vreference/Detail.html:24
	StreamDetailTable(qw422016, p, ps)
//line views/vreference/Detail.html:24
	qw422016.N().S(`
  </div>
`)
//line views/vreference/Detail.html:27
	qw422016.N().S(`  `)
//line views/vreference/Detail.html:28
	components.StreamJSONModal(qw422016, "reference", "Reference JSON", p.Model, 1)
//line views/vreference/Detail.html:28
	qw422016.N().S(`
`)
//line views/vreference/Detail.html:29
}

//line views/vreference/Detail.html:29
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vreference/Detail.html:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vreference/Detail.html:29
	p.StreamBody(qw422016, as, ps)
//line views/vreference/Detail.html:29
	qt422016.ReleaseWriter(qw422016)
//line views/vreference/Detail.html:29
}

//line views/vreference/Detail.html:29
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vreference/Detail.html:29
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vreference/Detail.html:29
	p.WriteBody(qb422016, as, ps)
//line views/vreference/Detail.html:29
	qs422016 := string(qb422016.B)
//line views/vreference/Detail.html:29
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vreference/Detail.html:29
	return qs422016
//line views/vreference/Detail.html:29
}

//line views/vreference/Detail.html:31
func StreamDetailTable(qw422016 *qt422016.Writer, p *Detail, ps *cutil.PageState) {
//line views/vreference/Detail.html:31
	qw422016.N().S(`
  <div class="mt overflow full-width">
    <table>
      <tbody>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
          <td>`)
//line views/vreference/Detail.html:37
	view.StreamUUID(qw422016, &p.Model.ID)
//line views/vreference/Detail.html:37
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="[Custom], as a JSON object">Custom</th>
          <td>`)
//line views/vreference/Detail.html:41
	components.StreamJSON(qw422016, p.Model.Custom)
//line views/vreference/Detail.html:41
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="[SelfCustom], as a JSON object">Self</th>
          <td>`)
//line views/vreference/Detail.html:45
	components.StreamJSON(qw422016, p.Model.Self)
//line views/vreference/Detail.html:45
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Created</th>
          <td>`)
//line views/vreference/Detail.html:49
	view.StreamTimestamp(qw422016, &p.Model.Created)
//line views/vreference/Detail.html:49
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vreference/Detail.html:54
}

//line views/vreference/Detail.html:54
func WriteDetailTable(qq422016 qtio422016.Writer, p *Detail, ps *cutil.PageState) {
//line views/vreference/Detail.html:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vreference/Detail.html:54
	StreamDetailTable(qw422016, p, ps)
//line views/vreference/Detail.html:54
	qt422016.ReleaseWriter(qw422016)
//line views/vreference/Detail.html:54
}

//line views/vreference/Detail.html:54
func DetailTable(p *Detail, ps *cutil.PageState) string {
//line views/vreference/Detail.html:54
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vreference/Detail.html:54
	WriteDetailTable(qb422016, p, ps)
//line views/vreference/Detail.html:54
	qs422016 := string(qb422016.B)
//line views/vreference/Detail.html:54
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vreference/Detail.html:54
	return qs422016
//line views/vreference/Detail.html:54
}
