// Code generated by qtc from "Table.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vreference/Table.html:2
package vreference

//line views/vreference/Table.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/app/reference"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/view"
)

//line views/vreference/Table.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vreference/Table.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vreference/Table.html:11
func StreamTable(qw422016 *qt422016.Writer, models reference.References, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vreference/Table.html:11
	qw422016.N().S(`
`)
//line views/vreference/Table.html:12
	prms := params.Sanitized("reference", ps.Logger)

//line views/vreference/Table.html:12
	qw422016.N().S(`  <div class="overflow clear">
    <table>
      <thead>
        <tr>
          `)
//line views/vreference/Table.html:17
	components.StreamTableHeaderSimple(qw422016, "reference", "id", "ID", "UUID in format (00000000-0000-0000-0000-000000000000)", prms, ps.URI, ps)
//line views/vreference/Table.html:17
	qw422016.N().S(`
          `)
//line views/vreference/Table.html:18
	components.StreamTableHeaderSimple(qw422016, "reference", "custom", "Custom", "[Custom], as a JSON object", prms, ps.URI, ps)
//line views/vreference/Table.html:18
	qw422016.N().S(`
          `)
//line views/vreference/Table.html:19
	components.StreamTableHeaderSimple(qw422016, "reference", "self", "Self", "[SelfCustom], as a JSON object", prms, ps.URI, ps)
//line views/vreference/Table.html:19
	qw422016.N().S(`
          `)
//line views/vreference/Table.html:20
	components.StreamTableHeaderSimple(qw422016, "reference", "created", "Created", "Date and time, in almost any format", prms, ps.URI, ps)
//line views/vreference/Table.html:20
	qw422016.N().S(`
        </tr>
      </thead>
      <tbody>
`)
//line views/vreference/Table.html:24
	for _, model := range models {
//line views/vreference/Table.html:24
		qw422016.N().S(`        <tr>
          <td><a href="/reference/`)
//line views/vreference/Table.html:26
		view.StreamUUID(qw422016, &model.ID)
//line views/vreference/Table.html:26
		qw422016.N().S(`">`)
//line views/vreference/Table.html:26
		view.StreamUUID(qw422016, &model.ID)
//line views/vreference/Table.html:26
		qw422016.N().S(`</a></td>
          <td>`)
//line views/vreference/Table.html:27
		components.StreamJSON(qw422016, model.Custom)
//line views/vreference/Table.html:27
		qw422016.N().S(`</td>
          <td>`)
//line views/vreference/Table.html:28
		components.StreamJSON(qw422016, model.Self)
//line views/vreference/Table.html:28
		qw422016.N().S(`</td>
          <td>`)
//line views/vreference/Table.html:29
		view.StreamTimestamp(qw422016, &model.Created)
//line views/vreference/Table.html:29
		qw422016.N().S(`</td>
        </tr>
`)
//line views/vreference/Table.html:31
	}
//line views/vreference/Table.html:31
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vreference/Table.html:35
	if prms.HasNextPage(len(models)+prms.Offset) || prms.HasPreviousPage() {
//line views/vreference/Table.html:35
		qw422016.N().S(`  <hr />
  `)
//line views/vreference/Table.html:37
		components.StreamPagination(qw422016, len(models)+prms.Offset, prms, ps.URI)
//line views/vreference/Table.html:37
		qw422016.N().S(`
  <div class="clear"></div>
`)
//line views/vreference/Table.html:39
	}
//line views/vreference/Table.html:40
}

//line views/vreference/Table.html:40
func WriteTable(qq422016 qtio422016.Writer, models reference.References, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vreference/Table.html:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vreference/Table.html:40
	StreamTable(qw422016, models, params, as, ps)
//line views/vreference/Table.html:40
	qt422016.ReleaseWriter(qw422016)
//line views/vreference/Table.html:40
}

//line views/vreference/Table.html:40
func Table(models reference.References, params filter.ParamSet, as *app.State, ps *cutil.PageState) string {
//line views/vreference/Table.html:40
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vreference/Table.html:40
	WriteTable(qb422016, models, params, as, ps)
//line views/vreference/Table.html:40
	qs422016 := string(qb422016.B)
//line views/vreference/Table.html:40
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vreference/Table.html:40
	return qs422016
//line views/vreference/Table.html:40
}
