// Code generated by qtc from "Table.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vreference/Table.html:2
package vreference

//line views/vreference/Table.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/app/reference"
	"github.com/kyleu/pftest/views/components"
)

//line views/vreference/Table.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vreference/Table.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vreference/Table.html:10
func StreamTable(qw422016 *qt422016.Writer, models reference.References, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vreference/Table.html:10
	qw422016.N().S(`
`)
//line views/vreference/Table.html:11
	prms := params.Get("reference", nil, ps.Logger).Sanitize("reference")

//line views/vreference/Table.html:11
	qw422016.N().S(`  <table>
    <thead>
      <tr>
        `)
//line views/vreference/Table.html:15
	components.StreamTableHeaderSimple(qw422016, "reference", "id", "ID", "UUID in format (00000000-0000-0000-0000-000000000000)", prms, ps.URI, ps)
//line views/vreference/Table.html:15
	qw422016.N().S(`
        `)
//line views/vreference/Table.html:16
	components.StreamTableHeaderSimple(qw422016, "reference", "custom", "Custom", "[Custom], as a JSON object", prms, ps.URI, ps)
//line views/vreference/Table.html:16
	qw422016.N().S(`
        `)
//line views/vreference/Table.html:17
	components.StreamTableHeaderSimple(qw422016, "reference", "self", "Self", "[SelfCustom], as a JSON object", prms, ps.URI, ps)
//line views/vreference/Table.html:17
	qw422016.N().S(`
        `)
//line views/vreference/Table.html:18
	components.StreamTableHeaderSimple(qw422016, "reference", "created", "Created", "Date and time, in almost any format", prms, ps.URI, ps)
//line views/vreference/Table.html:18
	qw422016.N().S(`
      </tr>
    </thead>
    <tbody>
`)
//line views/vreference/Table.html:22
	for _, model := range models {
//line views/vreference/Table.html:22
		qw422016.N().S(`      <tr>
        <td><a href="/reference/`)
//line views/vreference/Table.html:24
		components.StreamDisplayUUID(qw422016, &model.ID)
//line views/vreference/Table.html:24
		qw422016.N().S(`">`)
//line views/vreference/Table.html:24
		components.StreamDisplayUUID(qw422016, &model.ID)
//line views/vreference/Table.html:24
		qw422016.N().S(`</a></td>
        <td>`)
//line views/vreference/Table.html:25
		components.StreamJSON(qw422016, model.Custom)
//line views/vreference/Table.html:25
		qw422016.N().S(`</td>
        <td>`)
//line views/vreference/Table.html:26
		components.StreamJSON(qw422016, model.Self)
//line views/vreference/Table.html:26
		qw422016.N().S(`</td>
        <td>`)
//line views/vreference/Table.html:27
		components.StreamDisplayTimestamp(qw422016, &model.Created)
//line views/vreference/Table.html:27
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vreference/Table.html:29
	}
//line views/vreference/Table.html:30
	if prms.HasNextPage(len(models)+prms.Offset) || prms.HasPreviousPage() {
//line views/vreference/Table.html:30
		qw422016.N().S(`      <tr>
        <td colspan="4">`)
//line views/vreference/Table.html:32
		components.StreamPagination(qw422016, len(models)+prms.Offset, prms, ps.URI)
//line views/vreference/Table.html:32
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vreference/Table.html:34
	}
//line views/vreference/Table.html:34
	qw422016.N().S(`    </tbody>
  </table>
`)
//line views/vreference/Table.html:37
}

//line views/vreference/Table.html:37
func WriteTable(qq422016 qtio422016.Writer, models reference.References, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vreference/Table.html:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vreference/Table.html:37
	StreamTable(qw422016, models, params, as, ps)
//line views/vreference/Table.html:37
	qt422016.ReleaseWriter(qw422016)
//line views/vreference/Table.html:37
}

//line views/vreference/Table.html:37
func Table(models reference.References, params filter.ParamSet, as *app.State, ps *cutil.PageState) string {
//line views/vreference/Table.html:37
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vreference/Table.html:37
	WriteTable(qb422016, models, params, as, ps)
//line views/vreference/Table.html:37
	qs422016 := string(qb422016.B)
//line views/vreference/Table.html:37
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vreference/Table.html:37
	return qs422016
//line views/vreference/Table.html:37
}
