// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vaudit/Detail.html:2
package vaudit

//line views/vaudit/Detail.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/audit"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vaudit/Detail.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaudit/Detail.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaudit/Detail.html:11
type Detail struct {
	layout.Basic
	Model   *audit.Audit
	Params  filter.ParamSet
	Records audit.Records
}

//line views/vaudit/Detail.html:18
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudit/Detail.html:18
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-audit"><button type="button">JSON</button></a>
      <a href="`)
//line views/vaudit/Detail.html:22
	qw422016.E().S(p.Model.WebPath())
//line views/vaudit/Detail.html:22
	qw422016.N().S(`/edit"><button>Edit</button></a>
    </div>
    <h3>`)
//line views/vaudit/Detail.html:24
	components.StreamSVGRefIcon(qw422016, `cog`, ps)
//line views/vaudit/Detail.html:24
	qw422016.N().S(` Audit [`)
//line views/vaudit/Detail.html:24
	qw422016.E().S(p.Model.String())
//line views/vaudit/Detail.html:24
	qw422016.N().S(`]</h3>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
          <td>`)
//line views/vaudit/Detail.html:29
	components.StreamDisplayUUID(qw422016, &p.Model.ID)
//line views/vaudit/Detail.html:29
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">App</th>
          <td>`)
//line views/vaudit/Detail.html:33
	qw422016.E().S(p.Model.App)
//line views/vaudit/Detail.html:33
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Act</th>
          <td>`)
//line views/vaudit/Detail.html:37
	qw422016.E().S(p.Model.Act)
//line views/vaudit/Detail.html:37
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Client</th>
          <td>`)
//line views/vaudit/Detail.html:41
	qw422016.E().S(p.Model.Client)
//line views/vaudit/Detail.html:41
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Server</th>
          <td>`)
//line views/vaudit/Detail.html:45
	qw422016.E().S(p.Model.Server)
//line views/vaudit/Detail.html:45
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">User</th>
          <td>`)
//line views/vaudit/Detail.html:49
	qw422016.E().S(p.Model.User)
//line views/vaudit/Detail.html:49
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="JSON object">Metadata</th>
          <td>`)
//line views/vaudit/Detail.html:53
	components.StreamJSON(qw422016, p.Model.Metadata)
//line views/vaudit/Detail.html:53
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Message</th>
          <td>`)
//line views/vaudit/Detail.html:57
	qw422016.E().S(p.Model.Message)
//line views/vaudit/Detail.html:57
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Started</th>
          <td>`)
//line views/vaudit/Detail.html:61
	components.StreamDisplayTimestamp(qw422016, &p.Model.Started)
//line views/vaudit/Detail.html:61
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format">Completed</th>
          <td>`)
//line views/vaudit/Detail.html:65
	components.StreamDisplayTimestamp(qw422016, &p.Model.Completed)
//line views/vaudit/Detail.html:65
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vaudit/Detail.html:72
	if len(p.Records) > 0 {
//line views/vaudit/Detail.html:72
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vaudit/Detail.html:74
		components.StreamSVGRefIcon(qw422016, `cog`, ps)
//line views/vaudit/Detail.html:74
		qw422016.N().S(` Audit Records</h3>
    `)
//line views/vaudit/Detail.html:75
		StreamRecordTable(qw422016, p.Records, p.Params, as, ps)
//line views/vaudit/Detail.html:75
		qw422016.N().S(`
  </div>
`)
//line views/vaudit/Detail.html:77
	}
//line views/vaudit/Detail.html:77
	qw422016.N().S(`  `)
//line views/vaudit/Detail.html:78
	components.StreamJSONModal(qw422016, "audit", "Audit JSON", p.Model, 1)
//line views/vaudit/Detail.html:78
	qw422016.N().S(`
`)
//line views/vaudit/Detail.html:79
}

//line views/vaudit/Detail.html:79
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudit/Detail.html:79
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaudit/Detail.html:79
	p.StreamBody(qw422016, as, ps)
//line views/vaudit/Detail.html:79
	qt422016.ReleaseWriter(qw422016)
//line views/vaudit/Detail.html:79
}

//line views/vaudit/Detail.html:79
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaudit/Detail.html:79
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaudit/Detail.html:79
	p.WriteBody(qb422016, as, ps)
//line views/vaudit/Detail.html:79
	qs422016 := string(qb422016.B)
//line views/vaudit/Detail.html:79
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaudit/Detail.html:79
	return qs422016
//line views/vaudit/Detail.html:79
}
