// Code generated by qtc from "Dashboard.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vnotebook/Dashboard.html:2
package vnotebook

//line views/vnotebook/Dashboard.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/util"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vnotebook/Dashboard.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vnotebook/Dashboard.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vnotebook/Dashboard.html:10
type Notebook struct {
	layout.Basic
}

//line views/vnotebook/Dashboard.html:14
func (p *Notebook) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vnotebook/Dashboard.html:14
	qw422016.N().S(`
  <style>
    html {
      height: 100%;
    }
    body {
      min-height: 100%;
    }
    .iframe-container {
      height: calc(100vh - var(--nav-height));
    }
    .iframe {
      width: 100%;
      height: calc(100% - 4px);
      border: 0;
    }
  </style>
  <div class="iframe-container">
    <h3 style="display: none;">`)
//line views/vnotebook/Dashboard.html:32
	components.StreamSVGRefIcon(qw422016, `notebook`, ps)
//line views/vnotebook/Dashboard.html:32
	qw422016.N().S(`Notebook</h3>
    <iframe class="iframe" src="http://localhost:`)
//line views/vnotebook/Dashboard.html:33
	qw422016.N().D(util.AppPort + 10)
//line views/vnotebook/Dashboard.html:33
	qw422016.N().S(`/"></iframe>
  </div>
`)
//line views/vnotebook/Dashboard.html:35
}

//line views/vnotebook/Dashboard.html:35
func (p *Notebook) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vnotebook/Dashboard.html:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vnotebook/Dashboard.html:35
	p.StreamBody(qw422016, as, ps)
//line views/vnotebook/Dashboard.html:35
	qt422016.ReleaseWriter(qw422016)
//line views/vnotebook/Dashboard.html:35
}

//line views/vnotebook/Dashboard.html:35
func (p *Notebook) Body(as *app.State, ps *cutil.PageState) string {
//line views/vnotebook/Dashboard.html:35
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vnotebook/Dashboard.html:35
	p.WriteBody(qb422016, as, ps)
//line views/vnotebook/Dashboard.html:35
	qs422016 := string(qb422016.B)
//line views/vnotebook/Dashboard.html:35
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vnotebook/Dashboard.html:35
	return qs422016
//line views/vnotebook/Dashboard.html:35
}
