// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vaudited/Detail.html:1
package vaudited

//line views/vaudited/Detail.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/audited"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/audit"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/view"
	"github.com/kyleu/pftest/views/layout"
	"github.com/kyleu/pftest/views/vaudit"
)

//line views/vaudited/Detail.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaudited/Detail.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaudited/Detail.html:13
type Detail struct {
	layout.Basic
	Model        *audited.Audited
	Params       filter.ParamSet
	AuditRecords audit.Records
}

//line views/vaudited/Detail.html:20
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudited/Detail.html:20
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-audited"><button type="button">`)
//line views/vaudited/Detail.html:23
	components.StreamSVGButton(qw422016, "file", ps)
//line views/vaudited/Detail.html:23
	qw422016.N().S(` JSON</button></a>
      <a href="`)
//line views/vaudited/Detail.html:24
	qw422016.E().S(p.Model.WebPath())
//line views/vaudited/Detail.html:24
	qw422016.N().S(`/edit"><button>`)
//line views/vaudited/Detail.html:24
	components.StreamSVGButton(qw422016, "edit", ps)
//line views/vaudited/Detail.html:24
	qw422016.N().S(` Edit</button></a>
    </div>
    <h3>`)
//line views/vaudited/Detail.html:26
	components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vaudited/Detail.html:26
	qw422016.N().S(` `)
//line views/vaudited/Detail.html:26
	qw422016.E().S(p.Model.TitleString())
//line views/vaudited/Detail.html:26
	qw422016.N().S(`</h3>
    <div><a href="/audited"><em>Audited</em></a></div>
    <div class="mt overflow full-width">
      <table>
        <tbody>
          <tr>
            <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
            <td>`)
//line views/vaudited/Detail.html:33
	view.StreamUUID(qw422016, &p.Model.ID)
//line views/vaudited/Detail.html:33
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Name</th>
            <td><strong>`)
//line views/vaudited/Detail.html:37
	view.StreamString(qw422016, p.Model.Name)
//line views/vaudited/Detail.html:37
	qw422016.N().S(`</strong></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
`)
//line views/vaudited/Detail.html:45
	if len(p.AuditRecords) > 0 {
//line views/vaudited/Detail.html:45
		qw422016.N().S(`  <div class="card">
    <h3>Audits</h3>
    `)
//line views/vaudited/Detail.html:48
		vaudit.StreamRecordTable(qw422016, p.AuditRecords, p.Params, as, ps)
//line views/vaudited/Detail.html:48
		qw422016.N().S(`
  </div>
`)
//line views/vaudited/Detail.html:50
	}
//line views/vaudited/Detail.html:50
	qw422016.N().S(`  `)
//line views/vaudited/Detail.html:51
	components.StreamJSONModal(qw422016, "audited", "Audited JSON", p.Model, 1)
//line views/vaudited/Detail.html:51
	qw422016.N().S(`
`)
//line views/vaudited/Detail.html:52
}

//line views/vaudited/Detail.html:52
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudited/Detail.html:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaudited/Detail.html:52
	p.StreamBody(qw422016, as, ps)
//line views/vaudited/Detail.html:52
	qt422016.ReleaseWriter(qw422016)
//line views/vaudited/Detail.html:52
}

//line views/vaudited/Detail.html:52
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaudited/Detail.html:52
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaudited/Detail.html:52
	p.WriteBody(qb422016, as, ps)
//line views/vaudited/Detail.html:52
	qs422016 := string(qb422016.B)
//line views/vaudited/Detail.html:52
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaudited/Detail.html:52
	return qs422016
//line views/vaudited/Detail.html:52
}
