// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vaudited/Detail.html:2
package vaudited

//line views/vaudited/Detail.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/audited"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/audit"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
	"github.com/kyleu/pftest/views/vaudit"
)

//line views/vaudited/Detail.html:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaudited/Detail.html:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaudited/Detail.html:13
type Detail struct {
	layout.Basic
	Model        *audited.Audited
	Params       filter.ParamSet
	AuditRecords audit.Records
}

//line views/vaudited/Detail.html:20
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudited/Detail.html:20
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-audited"><button type="button">JSON</button></a>
      <a href="`)
//line views/vaudited/Detail.html:24
	qw422016.E().S(p.Model.WebPath())
//line views/vaudited/Detail.html:24
	qw422016.N().S(`/edit"><button>`)
//line views/vaudited/Detail.html:24
	components.StreamSVGRef(qw422016, "edit", 15, 15, "icon", ps)
//line views/vaudited/Detail.html:24
	qw422016.N().S(`Edit</button></a>
    </div>
    <h3>`)
//line views/vaudited/Detail.html:26
	components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vaudited/Detail.html:26
	qw422016.N().S(` `)
//line views/vaudited/Detail.html:26
	qw422016.E().S(p.Model.TitleString())
//line views/vaudited/Detail.html:26
	qw422016.N().S(`</h3>
    <div><a href="/audited"><em>Audited</em></a></div>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
          <td>`)
//line views/vaudited/Detail.html:32
	components.StreamDisplayUUID(qw422016, &p.Model.ID)
//line views/vaudited/Detail.html:32
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Name</th>
          <td><strong>`)
//line views/vaudited/Detail.html:36
	qw422016.E().S(p.Model.Name)
//line views/vaudited/Detail.html:36
	qw422016.N().S(`</strong></td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vaudited/Detail.html:43
	if len(p.AuditRecords) > 0 {
//line views/vaudited/Detail.html:43
		qw422016.N().S(`  <div class="card">
    <h3>Audits</h3>
    `)
//line views/vaudited/Detail.html:46
		vaudit.StreamRecordTable(qw422016, p.AuditRecords, p.Params, as, ps)
//line views/vaudited/Detail.html:46
		qw422016.N().S(`
  </div>
`)
//line views/vaudited/Detail.html:48
	}
//line views/vaudited/Detail.html:48
	qw422016.N().S(`  `)
//line views/vaudited/Detail.html:49
	components.StreamJSONModal(qw422016, "audited", "Audited JSON", p.Model, 1)
//line views/vaudited/Detail.html:49
	qw422016.N().S(`
`)
//line views/vaudited/Detail.html:50
}

//line views/vaudited/Detail.html:50
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudited/Detail.html:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaudited/Detail.html:50
	p.StreamBody(qw422016, as, ps)
//line views/vaudited/Detail.html:50
	qt422016.ReleaseWriter(qw422016)
//line views/vaudited/Detail.html:50
}

//line views/vaudited/Detail.html:50
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaudited/Detail.html:50
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaudited/Detail.html:50
	p.WriteBody(qb422016, as, ps)
//line views/vaudited/Detail.html:50
	qs422016 := string(qb422016.B)
//line views/vaudited/Detail.html:50
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaudited/Detail.html:50
	return qs422016
//line views/vaudited/Detail.html:50
}
