// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vaudited/Detail.html:2
package vaudited

//line views/vaudited/Detail.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/audited"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vaudited/Detail.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaudited/Detail.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaudited/Detail.html:10
type Detail struct {
	layout.Basic
	Model *audited.Audited
}

//line views/vaudited/Detail.html:15
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudited/Detail.html:15
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-audited"><button type="button">JSON</button></a>
      <a href="`)
//line views/vaudited/Detail.html:19
	qw422016.E().S(p.Model.WebPath())
//line views/vaudited/Detail.html:19
	qw422016.N().S(`/edit"><button>`)
//line views/vaudited/Detail.html:19
	components.StreamSVGRef(qw422016, "edit", 15, 15, "icon", ps)
//line views/vaudited/Detail.html:19
	qw422016.N().S(`Edit</button></a>
    </div>
    <h3>`)
//line views/vaudited/Detail.html:21
	components.StreamSVGRefIcon(qw422016, `star`, ps)
//line views/vaudited/Detail.html:21
	qw422016.N().S(` `)
//line views/vaudited/Detail.html:21
	qw422016.E().S(p.Model.TitleString())
//line views/vaudited/Detail.html:21
	qw422016.N().S(`</h3>
    <div><a href="/audited"><em>Audited</em></a></div>
    <table class="mt">
      <tbody>
        <tr>
          <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
          <td>`)
//line views/vaudited/Detail.html:27
	components.StreamDisplayUUID(qw422016, &p.Model.ID)
//line views/vaudited/Detail.html:27
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Name</th>
          <td><strong>`)
//line views/vaudited/Detail.html:31
	qw422016.E().S(p.Model.Name)
//line views/vaudited/Detail.html:31
	qw422016.N().S(`</strong></td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vaudited/Detail.html:37
	qw422016.N().S(`  `)
//line views/vaudited/Detail.html:38
	components.StreamJSONModal(qw422016, "audited", "Audited JSON", p.Model, 1)
//line views/vaudited/Detail.html:38
	qw422016.N().S(`
`)
//line views/vaudited/Detail.html:39
}

//line views/vaudited/Detail.html:39
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudited/Detail.html:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaudited/Detail.html:39
	p.StreamBody(qw422016, as, ps)
//line views/vaudited/Detail.html:39
	qt422016.ReleaseWriter(qw422016)
//line views/vaudited/Detail.html:39
}

//line views/vaudited/Detail.html:39
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaudited/Detail.html:39
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaudited/Detail.html:39
	p.WriteBody(qb422016, as, ps)
//line views/vaudited/Detail.html:39
	qs422016 := string(qb422016.B)
//line views/vaudited/Detail.html:39
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaudited/Detail.html:39
	return qs422016
//line views/vaudited/Detail.html:39
}
