// Code generated by qtc from "Response.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vhar/Response.html:2
package vhar

//line views/vhar/Response.html:2
import (
	"fmt"

	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/har"
	"github.com/kyleu/pftest/app/util"
)

//line views/vhar/Response.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vhar/Response.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vhar/Response.html:10
func StreamRenderResponse(qw422016 *qt422016.Writer, key string, r *har.Response, ps *cutil.PageState) {
//line views/vhar/Response.html:10
	qw422016.N().S(`
  <table class="min-200 expanded">
    <tbody>
      <tr>
        <th class="shrink">Status</th>
        <td>`)
//line views/vhar/Response.html:15
	qw422016.N().D(r.Status)
//line views/vhar/Response.html:15
	qw422016.N().S(`: `)
//line views/vhar/Response.html:15
	qw422016.E().S(r.StatusText)
//line views/vhar/Response.html:15
	qw422016.N().S(`</td>
      </tr>
`)
//line views/vhar/Response.html:17
	if r.RedirectURL != "" {
//line views/vhar/Response.html:17
		qw422016.N().S(`      <tr>
        <th class="shrink">Redirect URL</th>
        <td>`)
//line views/vhar/Response.html:20
		qw422016.E().S(r.RedirectURL)
//line views/vhar/Response.html:20
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vhar/Response.html:22
	}
//line views/vhar/Response.html:22
	qw422016.N().S(`      <tr>
        <th class="shrink">Headers </th>
        <td>`)
//line views/vhar/Response.html:25
	streamrenderNVPsHidden(qw422016, fmt.Sprintf("response-header-%s", key), "Header", r.Headers, r.HeadersSize, ps)
//line views/vhar/Response.html:25
	qw422016.N().S(`</td>
      </tr>
      <tr>
        <th class="shrink">Content Type</th>
        <td>`)
//line views/vhar/Response.html:29
	qw422016.E().S(r.ContentType())
//line views/vhar/Response.html:29
	qw422016.N().S(`</td>
      </tr>
`)
//line views/vhar/Response.html:31
	if len(r.Cookies) > 0 {
//line views/vhar/Response.html:31
		qw422016.N().S(`      <tr>
        <th class="shrink">Cookies</th>
        <td>`)
//line views/vhar/Response.html:34
		streamrenderCookiesHidden(qw422016, fmt.Sprintf("response-cookies-%s", key), r.Cookies, ps)
//line views/vhar/Response.html:34
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vhar/Response.html:36
	}
//line views/vhar/Response.html:37
	if r.Content != nil && r.Content.Text != "" {
//line views/vhar/Response.html:37
		qw422016.N().S(`      <tr>
        <th class="shrink">Body</th>
        <td>
          <div class="right"><em>`)
//line views/vhar/Response.html:41
		qw422016.E().S(util.ByteSizeSI(int64(r.Content.Size)))
//line views/vhar/Response.html:41
		qw422016.N().S(`</em></div>
          <ul class="accordion">
            <li>
              <input id="accordion-response-body-`)
//line views/vhar/Response.html:44
		qw422016.E().S(key)
//line views/vhar/Response.html:44
		qw422016.N().S(`" type="checkbox" hidden />
              <label class="no-padding" for="accordion-response-body-`)
//line views/vhar/Response.html:45
		qw422016.E().S(key)
//line views/vhar/Response.html:45
		qw422016.N().S(`"><em>(click to show)</em></label>
              <div class="bd">
                <pre>`)
//line views/vhar/Response.html:47
		qw422016.E().S(r.Content.Text)
//line views/vhar/Response.html:47
		qw422016.N().S(`</pre>
              </div>
            </li>
          </ul>
        </td>
      </tr>
`)
//line views/vhar/Response.html:53
	}
//line views/vhar/Response.html:53
	qw422016.N().S(`    </tbody>
  </table>
`)
//line views/vhar/Response.html:56
}

//line views/vhar/Response.html:56
func WriteRenderResponse(qq422016 qtio422016.Writer, key string, r *har.Response, ps *cutil.PageState) {
//line views/vhar/Response.html:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhar/Response.html:56
	StreamRenderResponse(qw422016, key, r, ps)
//line views/vhar/Response.html:56
	qt422016.ReleaseWriter(qw422016)
//line views/vhar/Response.html:56
}

//line views/vhar/Response.html:56
func RenderResponse(key string, r *har.Response, ps *cutil.PageState) string {
//line views/vhar/Response.html:56
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhar/Response.html:56
	WriteRenderResponse(qb422016, key, r, ps)
//line views/vhar/Response.html:56
	qs422016 := string(qb422016.B)
//line views/vhar/Response.html:56
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhar/Response.html:56
	return qs422016
//line views/vhar/Response.html:56
}
