// Code generated by qtc from "Response.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vhar/Response.html:1
package vhar

//line views/vhar/Response.html:1
import (
	"fmt"
	"strings"

	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/har"
	"github.com/kyleu/pftest/app/util"
)

//line views/vhar/Response.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vhar/Response.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vhar/Response.html:10
func StreamRenderResponse(qw422016 *qt422016.Writer, key string, r *har.Response, ps *cutil.PageState) {
//line views/vhar/Response.html:10
	qw422016.N().S(`
  <div class="overflow full-width">
    <table class="min-200 expanded">
      <tbody>
        <tr>
          <th class="shrink">Status</th>
          <td>`)
//line views/vhar/Response.html:16
	qw422016.N().D(r.Status)
//line views/vhar/Response.html:16
	qw422016.N().S(`: `)
//line views/vhar/Response.html:16
	qw422016.E().S(r.StatusText)
//line views/vhar/Response.html:16
	qw422016.N().S(`</td>
        </tr>
`)
//line views/vhar/Response.html:18
	if r.RedirectURL != "" {
//line views/vhar/Response.html:18
		qw422016.N().S(`        <tr>
          <th class="shrink">Redirect URL</th>
          <td>`)
//line views/vhar/Response.html:21
		qw422016.E().S(r.RedirectURL)
//line views/vhar/Response.html:21
		qw422016.N().S(`</td>
        </tr>
`)
//line views/vhar/Response.html:23
	}
//line views/vhar/Response.html:23
	qw422016.N().S(`        <tr>
          <th class="shrink">Headers </th>
          <td>`)
//line views/vhar/Response.html:26
	streamrenderNVPsHidden(qw422016, fmt.Sprintf("response-header-%s", key), "Header", r.Headers, r.HeadersSize, ps)
//line views/vhar/Response.html:26
	qw422016.N().S(`</td>
        </tr>
`)
//line views/vhar/Response.html:28
	if len(r.Cookies) > 0 {
//line views/vhar/Response.html:28
		qw422016.N().S(`        <tr>
          <th class="shrink">Cookies</th>
          <td>`)
//line views/vhar/Response.html:31
		streamrenderCookiesHidden(qw422016, fmt.Sprintf("response-cookies-%s", key), r.Cookies, ps)
//line views/vhar/Response.html:31
		qw422016.N().S(`</td>
        </tr>
`)
//line views/vhar/Response.html:33
	}
//line views/vhar/Response.html:34
	if r.Content != nil && r.Content.Text != "" {
//line views/vhar/Response.html:34
		qw422016.N().S(`        <tr>
          <th class="shrink">Body</th>
          <td>
            <div class="right"><em>`)
//line views/vhar/Response.html:38
		if r.ContentType() != "" {
//line views/vhar/Response.html:38
			qw422016.E().S(r.ContentType())
//line views/vhar/Response.html:38
			qw422016.N().S(`, `)
//line views/vhar/Response.html:38
		}
//line views/vhar/Response.html:38
		qw422016.E().S(util.ByteSizeSI(int64(r.Content.Size)))
//line views/vhar/Response.html:38
		qw422016.N().S(`</em></div>
            <ul class="accordion">
              <li>
                <input id="accordion-response-body-`)
//line views/vhar/Response.html:41
		qw422016.E().S(key)
//line views/vhar/Response.html:41
		qw422016.N().S(`" type="checkbox" hidden="hidden" />
                <label class="no-padding" for="accordion-response-body-`)
//line views/vhar/Response.html:42
		qw422016.E().S(key)
//line views/vhar/Response.html:42
		qw422016.N().S(`"><em>(click to show)</em></label>
                <div class="bd"><div><div>
`)
//line views/vhar/Response.html:44
		if strings.HasPrefix(r.ContentType(), "image/") {
//line views/vhar/Response.html:44
			qw422016.N().S(`                  <img style="border: var(--border)" src="data:`)
//line views/vhar/Response.html:45
			qw422016.E().S(r.ContentType())
//line views/vhar/Response.html:45
			qw422016.N().S(`;base64,`)
//line views/vhar/Response.html:45
			qw422016.E().S(r.Content.Text)
//line views/vhar/Response.html:45
			qw422016.N().S(`" />
`)
//line views/vhar/Response.html:46
		} else {
//line views/vhar/Response.html:46
			qw422016.N().S(`                  <pre>`)
//line views/vhar/Response.html:47
			qw422016.E().S(r.Content.Text)
//line views/vhar/Response.html:47
			qw422016.N().S(`</pre>
`)
//line views/vhar/Response.html:48
		}
//line views/vhar/Response.html:48
		qw422016.N().S(`                </div></div></div>
              </li>
            </ul>
          </td>
        </tr>
`)
//line views/vhar/Response.html:54
	}
//line views/vhar/Response.html:54
	qw422016.N().S(`      </tbody>
    </table>
  </div>
`)
//line views/vhar/Response.html:58
}

//line views/vhar/Response.html:58
func WriteRenderResponse(qq422016 qtio422016.Writer, key string, r *har.Response, ps *cutil.PageState) {
//line views/vhar/Response.html:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vhar/Response.html:58
	StreamRenderResponse(qw422016, key, r, ps)
//line views/vhar/Response.html:58
	qt422016.ReleaseWriter(qw422016)
//line views/vhar/Response.html:58
}

//line views/vhar/Response.html:58
func RenderResponse(key string, r *har.Response, ps *cutil.PageState) string {
//line views/vhar/Response.html:58
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vhar/Response.html:58
	WriteRenderResponse(qb422016, key, r, ps)
//line views/vhar/Response.html:58
	qs422016 := string(qb422016.B)
//line views/vhar/Response.html:58
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vhar/Response.html:58
	return qs422016
//line views/vhar/Response.html:58
}
