// Code generated by qtc from "BrandIcons.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vadmin/BrandIcons.html:1
package vadmin

//line views/vadmin/BrandIcons.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/icons"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vadmin/BrandIcons.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vadmin/BrandIcons.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vadmin/BrandIcons.html:9
type BrandIcons struct {
	layout.Basic
	Library *icons.Library
}

//line views/vadmin/BrandIcons.html:14
func (p *BrandIcons) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/BrandIcons.html:14
	qw422016.N().S(`
  <style>
    .library {
      display: grid;
      grid-template-columns: repeat(auto-fill,minmax(13rem,1fr));
      margin: 0 0 1.5rem;
    }
    .brand-icon {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      overflow: hidden;
      margin: var(--padding);
      padding-bottom: var(--padding-small);
      border-bottom-width: var(--padding-small);
      border-bottom-style: solid;
    }
    .brand-icon .svg {
      width: 48px;
      height: 48px;
    }
  </style>
  <div class="card">
    <div class="right"><em>`)
//line views/vadmin/BrandIcons.html:38
	qw422016.N().D(len(p.Library.Icons))
//line views/vadmin/BrandIcons.html:38
	qw422016.N().S(` icons</em></div>
    <h3>`)
//line views/vadmin/BrandIcons.html:39
	components.StreamSVGIcon(qw422016, `image`, ps)
//line views/vadmin/BrandIcons.html:39
	qw422016.N().S(` Brand Icon Library</h3>
    <div class="mt library">
`)
//line views/vadmin/BrandIcons.html:41
	for _, key := range p.Library.SortedKeys() {
//line views/vadmin/BrandIcons.html:42
		x := p.Library.Icons[key]

//line views/vadmin/BrandIcons.html:42
		qw422016.N().S(`      <div class="brand-icon" style="border-color: #`)
//line views/vadmin/BrandIcons.html:43
		qw422016.E().S(x.Color)
//line views/vadmin/BrandIcons.html:43
		qw422016.N().S(`;" title="`)
//line views/vadmin/BrandIcons.html:43
		qw422016.E().S(x.Key)
//line views/vadmin/BrandIcons.html:43
		qw422016.N().S(`">
        <div class="svg">`)
//line views/vadmin/BrandIcons.html:44
		qw422016.N().S(x.HTML("brand-"))
//line views/vadmin/BrandIcons.html:44
		qw422016.N().S(`</div>
        <div>`)
//line views/vadmin/BrandIcons.html:45
		qw422016.E().S(x.Title)
//line views/vadmin/BrandIcons.html:45
		qw422016.N().S(`</div>
      </div>
`)
//line views/vadmin/BrandIcons.html:47
	}
//line views/vadmin/BrandIcons.html:47
	qw422016.N().S(`    </div>
  </div>
`)
//line views/vadmin/BrandIcons.html:50
}

//line views/vadmin/BrandIcons.html:50
func (p *BrandIcons) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/BrandIcons.html:50
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vadmin/BrandIcons.html:50
	p.StreamBody(qw422016, as, ps)
//line views/vadmin/BrandIcons.html:50
	qt422016.ReleaseWriter(qw422016)
//line views/vadmin/BrandIcons.html:50
}

//line views/vadmin/BrandIcons.html:50
func (p *BrandIcons) Body(as *app.State, ps *cutil.PageState) string {
//line views/vadmin/BrandIcons.html:50
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vadmin/BrandIcons.html:50
	p.WriteBody(qb422016, as, ps)
//line views/vadmin/BrandIcons.html:50
	qs422016 := string(qb422016.B)
//line views/vadmin/BrandIcons.html:50
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vadmin/BrandIcons.html:50
	return qs422016
//line views/vadmin/BrandIcons.html:50
}
