// Code generated by qtc from "BrandIcons.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vadmin/BrandIcons.html:2
package vadmin

//line views/vadmin/BrandIcons.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/icons"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vadmin/BrandIcons.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vadmin/BrandIcons.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vadmin/BrandIcons.html:10
type BrandIcons struct {
	layout.Basic
	Library *icons.Library
}

//line views/vadmin/BrandIcons.html:15
func (p *BrandIcons) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/BrandIcons.html:15
	qw422016.N().S(`
  <style>
    .library {
      display: grid;
      grid-template-columns: repeat(auto-fill,minmax(13rem,1fr));
      margin: 0 0 1.5rem;
    }
    .brand-icon {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      overflow: hidden;
      margin: var(--padding);
    }
    .brand-icon .svg {
      width: 48px;
      height: 48px;
    }
  </style>
  <div class="card">
    <h3>`)
//line views/vadmin/BrandIcons.html:36
	components.StreamSVGRefIcon(qw422016, `image`, ps)
//line views/vadmin/BrandIcons.html:36
	qw422016.N().S(`Brand Icon Library</h3>
    <div class="mt library">
`)
//line views/vadmin/BrandIcons.html:38
	for _, key := range p.Library.SortedKeys() {
//line views/vadmin/BrandIcons.html:39
		x := p.Library.Icons[key]

//line views/vadmin/BrandIcons.html:39
		qw422016.N().S(`      <div class="brand-icon" title="`)
//line views/vadmin/BrandIcons.html:40
		qw422016.E().S(x.Key)
//line views/vadmin/BrandIcons.html:40
		qw422016.N().S(`">
        <div class="svg">`)
//line views/vadmin/BrandIcons.html:41
		qw422016.N().S(x.HTML("brand-"))
//line views/vadmin/BrandIcons.html:41
		qw422016.N().S(`</div>
        <div>`)
//line views/vadmin/BrandIcons.html:42
		qw422016.E().S(x.Title)
//line views/vadmin/BrandIcons.html:42
		qw422016.N().S(`</div>
      </div>
`)
//line views/vadmin/BrandIcons.html:44
	}
//line views/vadmin/BrandIcons.html:44
	qw422016.N().S(`    </div>
  </div>
`)
//line views/vadmin/BrandIcons.html:47
}

//line views/vadmin/BrandIcons.html:47
func (p *BrandIcons) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/BrandIcons.html:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vadmin/BrandIcons.html:47
	p.StreamBody(qw422016, as, ps)
//line views/vadmin/BrandIcons.html:47
	qt422016.ReleaseWriter(qw422016)
//line views/vadmin/BrandIcons.html:47
}

//line views/vadmin/BrandIcons.html:47
func (p *BrandIcons) Body(as *app.State, ps *cutil.PageState) string {
//line views/vadmin/BrandIcons.html:47
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vadmin/BrandIcons.html:47
	p.WriteBody(qb422016, as, ps)
//line views/vadmin/BrandIcons.html:47
	qs422016 := string(qb422016.B)
//line views/vadmin/BrandIcons.html:47
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vadmin/BrandIcons.html:47
	return qs422016
//line views/vadmin/BrandIcons.html:47
}
