// Code generated by qtc from "Queue.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vadmin/Queue.html:1
package vadmin

//line views/vadmin/Queue.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/queue"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vadmin/Queue.html:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vadmin/Queue.html:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vadmin/Queue.html:9
type Queue struct {
	layout.Basic
	Status  *queue.Status
	Message *queue.Message
}

//line views/vadmin/Queue.html:15
func (p *Queue) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/Queue.html:15
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vadmin/Queue.html:17
	components.StreamSVGIcon(qw422016, `queue`, ps)
//line views/vadmin/Queue.html:17
	qw422016.N().S(` Queue Test</h3>
    <div class="mt">`)
//line views/vadmin/Queue.html:18
	components.StreamJSON(qw422016, p.Status)
//line views/vadmin/Queue.html:18
	qw422016.N().S(`</div>
  </div>
`)
//line views/vadmin/Queue.html:20
	if p.Message != nil {
//line views/vadmin/Queue.html:20
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vadmin/Queue.html:22
		components.StreamSVGIcon(qw422016, `cog`, ps)
//line views/vadmin/Queue.html:22
		qw422016.N().S(` Message</h3>
    <div class="mt">`)
//line views/vadmin/Queue.html:23
		components.StreamJSON(qw422016, p.Message)
//line views/vadmin/Queue.html:23
		qw422016.N().S(`</div>
  </div>
`)
//line views/vadmin/Queue.html:25
	}
//line views/vadmin/Queue.html:26
}

//line views/vadmin/Queue.html:26
func (p *Queue) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/Queue.html:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vadmin/Queue.html:26
	p.StreamBody(qw422016, as, ps)
//line views/vadmin/Queue.html:26
	qt422016.ReleaseWriter(qw422016)
//line views/vadmin/Queue.html:26
}

//line views/vadmin/Queue.html:26
func (p *Queue) Body(as *app.State, ps *cutil.PageState) string {
//line views/vadmin/Queue.html:26
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vadmin/Queue.html:26
	p.WriteBody(qb422016, as, ps)
//line views/vadmin/Queue.html:26
	qs422016 := string(qb422016.B)
//line views/vadmin/Queue.html:26
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vadmin/Queue.html:26
	return qs422016
//line views/vadmin/Queue.html:26
}
