// Code generated by qtc from "SettingsEdit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vadmin/SettingsEdit.html:1
package vadmin

//line views/vadmin/SettingsEdit.html:1
import (
	"net/http"

	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/settings"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/edit"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vadmin/SettingsEdit.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vadmin/SettingsEdit.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vadmin/SettingsEdit.html:12
type SettingsEdit struct {
	layout.Basic
	Settings *settings.Settings
}

//line views/vadmin/SettingsEdit.html:17
func (p *SettingsEdit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/SettingsEdit.html:17
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/vadmin/SettingsEdit.html:19
	components.StreamSVGIcon(qw422016, "edit", ps)
//line views/vadmin/SettingsEdit.html:19
	qw422016.N().S(` Edit App Settings</h3>
    <div class="mts"><em>Changes will be saved as <code>settings.json</code> in the configuration directory</em></div>
    `)
//line views/vadmin/SettingsEdit.html:21
	edit.StreamTableEditor(qw422016, "settings", settings.SettingsFieldDescs, p.Settings.ToMap(), "", http.MethodPost, "Save Changes")
//line views/vadmin/SettingsEdit.html:21
	qw422016.N().S(`
  </div>
`)
//line views/vadmin/SettingsEdit.html:23
}

//line views/vadmin/SettingsEdit.html:23
func (p *SettingsEdit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vadmin/SettingsEdit.html:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vadmin/SettingsEdit.html:23
	p.StreamBody(qw422016, as, ps)
//line views/vadmin/SettingsEdit.html:23
	qt422016.ReleaseWriter(qw422016)
//line views/vadmin/SettingsEdit.html:23
}

//line views/vadmin/SettingsEdit.html:23
func (p *SettingsEdit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vadmin/SettingsEdit.html:23
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vadmin/SettingsEdit.html:23
	p.WriteBody(qb422016, as, ps)
//line views/vadmin/SettingsEdit.html:23
	qs422016 := string(qb422016.B)
//line views/vadmin/SettingsEdit.html:23
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vadmin/SettingsEdit.html:23
	return qs422016
//line views/vadmin/SettingsEdit.html:23
}
