// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vtrouble/Detail.html:1
package vtrouble

//line views/vtrouble/Detail.html:1
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/trouble"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/view"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vtrouble/Detail.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vtrouble/Detail.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vtrouble/Detail.html:10
type Detail struct {
	layout.Basic
	Model *trouble.Trouble
	Paths []string
}

//line views/vtrouble/Detail.html:16
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtrouble/Detail.html:16
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-trouble"><button type="button">`)
//line views/vtrouble/Detail.html:19
	components.StreamSVGButton(qw422016, "file", ps)
//line views/vtrouble/Detail.html:19
	qw422016.N().S(` JSON</button></a>
      <a href="`)
//line views/vtrouble/Detail.html:20
	qw422016.E().S(p.Model.WebPath(p.Paths...))
//line views/vtrouble/Detail.html:20
	qw422016.N().S(`/edit"><button>`)
//line views/vtrouble/Detail.html:20
	components.StreamSVGButton(qw422016, "edit", ps)
//line views/vtrouble/Detail.html:20
	qw422016.N().S(` Edit</button></a>
    </div>
    <h3>`)
//line views/vtrouble/Detail.html:22
	components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vtrouble/Detail.html:22
	qw422016.N().S(` `)
//line views/vtrouble/Detail.html:22
	qw422016.E().S(p.Model.TitleString())
//line views/vtrouble/Detail.html:22
	qw422016.N().S(`</h3>
    <div><a href="`)
//line views/vtrouble/Detail.html:23
	qw422016.E().S(trouble.Route(p.Paths...))
//line views/vtrouble/Detail.html:23
	qw422016.N().S(`"><em>Trouble</em></a></div>
    `)
//line views/vtrouble/Detail.html:24
	StreamDetailTable(qw422016, p, ps)
//line views/vtrouble/Detail.html:24
	qw422016.N().S(`
  </div>
`)
//line views/vtrouble/Detail.html:27
	qw422016.N().S(`  `)
//line views/vtrouble/Detail.html:28
	components.StreamJSONModal(qw422016, "trouble", "Trouble JSON", p.Model, 1)
//line views/vtrouble/Detail.html:28
	qw422016.N().S(`
`)
//line views/vtrouble/Detail.html:29
}

//line views/vtrouble/Detail.html:29
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtrouble/Detail.html:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vtrouble/Detail.html:29
	p.StreamBody(qw422016, as, ps)
//line views/vtrouble/Detail.html:29
	qt422016.ReleaseWriter(qw422016)
//line views/vtrouble/Detail.html:29
}

//line views/vtrouble/Detail.html:29
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vtrouble/Detail.html:29
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vtrouble/Detail.html:29
	p.WriteBody(qb422016, as, ps)
//line views/vtrouble/Detail.html:29
	qs422016 := string(qb422016.B)
//line views/vtrouble/Detail.html:29
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vtrouble/Detail.html:29
	return qs422016
//line views/vtrouble/Detail.html:29
}

//line views/vtrouble/Detail.html:31
func StreamDetailTable(qw422016 *qt422016.Writer, p *Detail, ps *cutil.PageState) {
//line views/vtrouble/Detail.html:31
	qw422016.N().S(`
  <div class="mt overflow full-width">
    <table>
      <tbody>
        <tr>
          <th class="shrink" title="String text">From</th>
          <td>`)
//line views/vtrouble/Detail.html:37
	view.StreamString(qw422016, p.Model.From)
//line views/vtrouble/Detail.html:37
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Comma-separated list of values">Where</th>
          <td>`)
//line views/vtrouble/Detail.html:41
	view.StreamStringArray(qw422016, p.Model.Where)
//line views/vtrouble/Detail.html:41
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Integer">Selectcol</th>
          <td>`)
//line views/vtrouble/Detail.html:45
	qw422016.N().D(p.Model.Selectcol)
//line views/vtrouble/Detail.html:45
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Limit</th>
          <td>`)
//line views/vtrouble/Detail.html:49
	view.StreamString(qw422016, p.Model.Limit)
//line views/vtrouble/Detail.html:49
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="String text">Group</th>
          <td>`)
//line views/vtrouble/Detail.html:53
	view.StreamString(qw422016, p.Model.Group)
//line views/vtrouble/Detail.html:53
	qw422016.N().S(`</td>
        </tr>
        <tr>
          <th class="shrink" title="Date and time, in almost any format (optional)">Delete</th>
          <td>`)
//line views/vtrouble/Detail.html:57
	view.StreamTimestamp(qw422016, p.Model.Delete)
//line views/vtrouble/Detail.html:57
	qw422016.N().S(`</td>
        </tr>
      </tbody>
    </table>
  </div>
`)
//line views/vtrouble/Detail.html:62
}

//line views/vtrouble/Detail.html:62
func WriteDetailTable(qq422016 qtio422016.Writer, p *Detail, ps *cutil.PageState) {
//line views/vtrouble/Detail.html:62
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vtrouble/Detail.html:62
	StreamDetailTable(qw422016, p, ps)
//line views/vtrouble/Detail.html:62
	qt422016.ReleaseWriter(qw422016)
//line views/vtrouble/Detail.html:62
}

//line views/vtrouble/Detail.html:62
func DetailTable(p *Detail, ps *cutil.PageState) string {
//line views/vtrouble/Detail.html:62
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vtrouble/Detail.html:62
	WriteDetailTable(qb422016, p, ps)
//line views/vtrouble/Detail.html:62
	qs422016 := string(qb422016.B)
//line views/vtrouble/Detail.html:62
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vtrouble/Detail.html:62
	return qs422016
//line views/vtrouble/Detail.html:62
}
