// Code generated by qtc from "Edit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vtrouble/Edit.html:2
package vtrouble

//line views/vtrouble/Edit.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/trouble"
	"github.com/kyleu/pftest/app/util"
	"github.com/kyleu/pftest/views/components"
	"github.com/kyleu/pftest/views/components/edit"
	"github.com/kyleu/pftest/views/layout"
)

//line views/vtrouble/Edit.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vtrouble/Edit.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vtrouble/Edit.html:12
type Edit struct {
	layout.Basic
	Model *trouble.Trouble
	IsNew bool
}

//line views/vtrouble/Edit.html:18
func (p *Edit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtrouble/Edit.html:18
	qw422016.N().S(`
  <div class="card">
`)
//line views/vtrouble/Edit.html:20
	if p.IsNew {
//line views/vtrouble/Edit.html:20
		qw422016.N().S(`    <div class="right"><a href="?prototype=random"><button>Random</button></a></div>
    <h3>`)
//line views/vtrouble/Edit.html:22
		components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vtrouble/Edit.html:22
		qw422016.N().S(` New Trouble</h3>
    <form action="/troub/le/_new" class="mt" method="post">
`)
//line views/vtrouble/Edit.html:24
	} else {
//line views/vtrouble/Edit.html:24
		qw422016.N().S(`    <div class="right"><a class="link-confirm" href="`)
//line views/vtrouble/Edit.html:25
		qw422016.E().S(p.Model.WebPath())
//line views/vtrouble/Edit.html:25
		qw422016.N().S(`/delete" data-message="Are you sure you wish to delete trouble [`)
//line views/vtrouble/Edit.html:25
		qw422016.E().S(p.Model.String())
//line views/vtrouble/Edit.html:25
		qw422016.N().S(`]?"><button>`)
//line views/vtrouble/Edit.html:25
		components.StreamSVGButton(qw422016, "times", ps)
//line views/vtrouble/Edit.html:25
		qw422016.N().S(`Delete</button></a></div>
    <h3>`)
//line views/vtrouble/Edit.html:26
		components.StreamSVGIcon(qw422016, `star`, ps)
//line views/vtrouble/Edit.html:26
		qw422016.N().S(` Edit Trouble [`)
//line views/vtrouble/Edit.html:26
		qw422016.E().S(p.Model.String())
//line views/vtrouble/Edit.html:26
		qw422016.N().S(`]</h3>
    <form action="" method="post">
`)
//line views/vtrouble/Edit.html:28
	}
//line views/vtrouble/Edit.html:28
	qw422016.N().S(`      <table class="mt expanded">
        <tbody>
          `)
//line views/vtrouble/Edit.html:31
	if p.IsNew {
//line views/vtrouble/Edit.html:31
		edit.StreamStringTable(qw422016, "from", "", "From", p.Model.From, 5, "String text")
//line views/vtrouble/Edit.html:31
	}
//line views/vtrouble/Edit.html:31
	qw422016.N().S(`
          `)
//line views/vtrouble/Edit.html:32
	if p.IsNew {
//line views/vtrouble/Edit.html:32
		edit.StreamTextareaTable(qw422016, "where", "", "Where", 8, util.ToJSON(p.Model.Where), 5, "Comma-separated list of values")
//line views/vtrouble/Edit.html:32
	}
//line views/vtrouble/Edit.html:32
	qw422016.N().S(`
          `)
//line views/vtrouble/Edit.html:33
	edit.StreamIntTable(qw422016, "selectcol", "", "Selectcol", p.Model.Selectcol, 5, "Integer")
//line views/vtrouble/Edit.html:33
	qw422016.N().S(`
          `)
//line views/vtrouble/Edit.html:34
	edit.StreamStringTable(qw422016, "limit", "", "Limit", p.Model.Limit, 5, "String text")
//line views/vtrouble/Edit.html:34
	qw422016.N().S(`
          `)
//line views/vtrouble/Edit.html:35
	edit.StreamStringTable(qw422016, "group", "", "Group", p.Model.Group, 5, "String text")
//line views/vtrouble/Edit.html:35
	qw422016.N().S(`
          `)
//line views/vtrouble/Edit.html:36
	edit.StreamTimestampTable(qw422016, "delete", "", "Delete", p.Model.Delete, 5, "Date and time, in almost any format (optional)")
//line views/vtrouble/Edit.html:36
	qw422016.N().S(`
          <tr><td colspan="2"><button type="submit">Save Changes</button></td></tr>
        </tbody>
      </table>
    </form>
  </div>
`)
//line views/vtrouble/Edit.html:42
}

//line views/vtrouble/Edit.html:42
func (p *Edit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vtrouble/Edit.html:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vtrouble/Edit.html:42
	p.StreamBody(qw422016, as, ps)
//line views/vtrouble/Edit.html:42
	qt422016.ReleaseWriter(qw422016)
//line views/vtrouble/Edit.html:42
}

//line views/vtrouble/Edit.html:42
func (p *Edit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vtrouble/Edit.html:42
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vtrouble/Edit.html:42
	p.WriteBody(qb422016, as, ps)
//line views/vtrouble/Edit.html:42
	qs422016 := string(qb422016.B)
//line views/vtrouble/Edit.html:42
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vtrouble/Edit.html:42
	return qs422016
//line views/vtrouble/Edit.html:42
}
