// Code generated by qtc from "Table.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vtrouble/Table.html:2
package vtrouble

//line views/vtrouble/Table.html:2
import (
	"github.com/kyleu/pftest/app"
	"github.com/kyleu/pftest/app/controller/cutil"
	"github.com/kyleu/pftest/app/lib/filter"
	"github.com/kyleu/pftest/app/trouble"
	"github.com/kyleu/pftest/views/components"
)

//line views/vtrouble/Table.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vtrouble/Table.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vtrouble/Table.html:10
func StreamTable(qw422016 *qt422016.Writer, models trouble.Troubles, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vtrouble/Table.html:10
	qw422016.N().S(`
`)
//line views/vtrouble/Table.html:11
	prms := params.Get("trouble", nil, ps.Logger).Sanitize("trouble")

//line views/vtrouble/Table.html:11
	qw422016.N().S(`  <table class="mt">
    <thead>
      <tr>
        `)
//line views/vtrouble/Table.html:15
	components.StreamTableHeaderSimple(qw422016, "trouble", "from", "From", "String text", prms, ps.URI, ps)
//line views/vtrouble/Table.html:15
	qw422016.N().S(`
        `)
//line views/vtrouble/Table.html:16
	components.StreamTableHeaderSimple(qw422016, "trouble", "where", "Where", "Comma-separated list of values", prms, ps.URI, ps)
//line views/vtrouble/Table.html:16
	qw422016.N().S(`
        `)
//line views/vtrouble/Table.html:17
	components.StreamTableHeaderSimple(qw422016, "trouble", "selectcol", "Selectcol", "Integer", prms, ps.URI, ps)
//line views/vtrouble/Table.html:17
	qw422016.N().S(`
        `)
//line views/vtrouble/Table.html:18
	components.StreamTableHeaderSimple(qw422016, "trouble", "limit", "Limit", "String text", prms, ps.URI, ps)
//line views/vtrouble/Table.html:18
	qw422016.N().S(`
        `)
//line views/vtrouble/Table.html:19
	components.StreamTableHeaderSimple(qw422016, "trouble", "group", "Group", "String text", prms, ps.URI, ps)
//line views/vtrouble/Table.html:19
	qw422016.N().S(`
        `)
//line views/vtrouble/Table.html:20
	components.StreamTableHeaderSimple(qw422016, "trouble", "delete", "Delete", "Date and time, in almost any format (optional)", prms, ps.URI, ps)
//line views/vtrouble/Table.html:20
	qw422016.N().S(`
      </tr>
    </thead>
    <tbody>
`)
//line views/vtrouble/Table.html:24
	for _, model := range models {
//line views/vtrouble/Table.html:24
		qw422016.N().S(`      <tr>
        <td><a href="/troub/le/`)
//line views/vtrouble/Table.html:26
		qw422016.N().U(model.From)
//line views/vtrouble/Table.html:26
		qw422016.N().S(`/`)
//line views/vtrouble/Table.html:26
		components.StreamDisplayStringArray(qw422016, model.Where)
//line views/vtrouble/Table.html:26
		qw422016.N().S(`">`)
//line views/vtrouble/Table.html:26
		qw422016.E().S(model.From)
//line views/vtrouble/Table.html:26
		qw422016.N().S(`</a></td>
        <td><a href="/troub/le/`)
//line views/vtrouble/Table.html:27
		qw422016.N().U(model.From)
//line views/vtrouble/Table.html:27
		qw422016.N().S(`/`)
//line views/vtrouble/Table.html:27
		components.StreamDisplayStringArray(qw422016, model.Where)
//line views/vtrouble/Table.html:27
		qw422016.N().S(`">`)
//line views/vtrouble/Table.html:27
		components.StreamDisplayStringArray(qw422016, model.Where)
//line views/vtrouble/Table.html:27
		qw422016.N().S(`</a></td>
        <td>`)
//line views/vtrouble/Table.html:28
		qw422016.N().D(model.Selectcol)
//line views/vtrouble/Table.html:28
		qw422016.N().S(`</td>
        <td>`)
//line views/vtrouble/Table.html:29
		qw422016.E().S(model.Limit)
//line views/vtrouble/Table.html:29
		qw422016.N().S(`</td>
        <td>`)
//line views/vtrouble/Table.html:30
		qw422016.E().S(model.Group)
//line views/vtrouble/Table.html:30
		qw422016.N().S(`</td>
        <td>`)
//line views/vtrouble/Table.html:31
		components.StreamDisplayTimestamp(qw422016, model.Delete)
//line views/vtrouble/Table.html:31
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vtrouble/Table.html:33
	}
//line views/vtrouble/Table.html:34
	if prms.HasNextPage(len(models)+prms.Offset) || prms.HasPreviousPage() {
//line views/vtrouble/Table.html:34
		qw422016.N().S(`      <tr>
        <td colspan="6">`)
//line views/vtrouble/Table.html:36
		components.StreamPagination(qw422016, len(models)+prms.Offset, prms, ps.URI)
//line views/vtrouble/Table.html:36
		qw422016.N().S(`</td>
      </tr>
`)
//line views/vtrouble/Table.html:38
	}
//line views/vtrouble/Table.html:38
	qw422016.N().S(`    </tbody>
  </table>
`)
//line views/vtrouble/Table.html:41
}

//line views/vtrouble/Table.html:41
func WriteTable(qq422016 qtio422016.Writer, models trouble.Troubles, params filter.ParamSet, as *app.State, ps *cutil.PageState) {
//line views/vtrouble/Table.html:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vtrouble/Table.html:41
	StreamTable(qw422016, models, params, as, ps)
//line views/vtrouble/Table.html:41
	qt422016.ReleaseWriter(qw422016)
//line views/vtrouble/Table.html:41
}

//line views/vtrouble/Table.html:41
func Table(models trouble.Troubles, params filter.ParamSet, as *app.State, ps *cutil.PageState) string {
//line views/vtrouble/Table.html:41
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vtrouble/Table.html:41
	WriteTable(qb422016, models, params, as, ps)
//line views/vtrouble/Table.html:41
	qs422016 := string(qb422016.B)
//line views/vtrouble/Table.html:41
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vtrouble/Table.html:41
	return qs422016
//line views/vtrouble/Table.html:41
}
