# Content managed by Project Forge, see [projectforge.md] for details.
name: playwright
on:
  push:
    tags:
      - "*"
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
permissions:
  contents: write
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./test/playwright
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./test/playwright
        run: npx playwright install --with-deps

      - name: "Golang"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.21"

      - name: "Cache"
        uses: "actions/cache@v2"
        with:
          path: "~/go/pkg/mod"
          key: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "CI Build"
        run: "bin/bootstrap.sh"

      - name: "CI Build"
        run: "bin/build/fullbuild.sh"

      - name: "Debug2"
        run: "ls ./build/linux/amd64"
